In [75]:
import pandas as pd 
import numpy as np
import datetime

8B5221H4

In [76]:
vf=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_rawdata.csv',sep=',')
vf.info()

<class 'pandas.DataFrame'>
RangeIndex: 8834 entries, 0 to 8833
Data columns (total 50 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     8834 non-null   int64
 1   Sequence #                 0 non-null      float64
 2   Server Time                8834 non-null   str
 3   Unit Time                  8834 non-null   str
 4   Last Message Time          8834 non-null   str
 5   Latitude                   8834 non-null   float64
 6   Longitude                  8834 non-null   float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 8834 non-null   str
 9   Raw Event                  8834 non-null   str
 10  Address                    8832 non-null   str
 11  GPS Speed                  7026 non-null   float64
 12  ECU Speed                  0 non-null      float64
 13  Speed Limit                1403 non-null   float64
 14  Heading                    8732 non-null   float64
 15  Ignition Status            8834 non-null   str
 16  Notification Type          8834 non-null   str
 17  Trip Id                    8521 non-null   str
 18  Picture Id                 2098 non-null   float64
 19  Event Category             261 non-null    str
 20  Event Level                261 non-null    str
 21  Camera Clip Key            261 non-null    float64
 22  Camera Clip Offset         261 non-null    float64
 23  Clip Id                    261 non-null    float64
 24  Duration                   0 non-null      float64
 25  Rotate                     2098 non-null   str
 26  Camera Status              0 non-null      float64
 27  Idle Status                3068 non-null   str
 28  SDCard Status              0 non-null      float64
 29  Data Usage In KB           0 non-null      float64
 30  Transaction Id             0 non-null      float64
 31  Status                     0 non-null      float64
 32  Error Msg                  0 non-null      float64
 33  Valid Time Range           0 non-null      float64
 34  Warning                    0 non-null      float64
 35  Distance                   8832 non-null   float64
 36  Accumulated Distance       1941 non-null   float64
 37  Engine Hours               8834 non-null   float64
 38  Engine Hours + Off         8834 non-null   float64
 39  ECU Engine Hours           8834 non-null   int64
 40  ECU Engine Hours + Off     8834 non-null   int64
 41  Engine Odometer            8834 non-null   float64
 42  Engine Odometer + Off      8834 non-null   float64
 43  ECU Engine Odometer        8834 non-null   int64
 44  ECU Engine Odometer + Off  8834 non-null   int64
 45  HDOP                       5750 non-null   float64
 46  VDOP                       0 non-null      float64
 47  RSSI                       0 non-null      float64
 48  Battery Level              0 non-null      float64
 49  Raw Data                   8834 non-null   str
dtypes: float64(31), int64(5), str(14)
memory usage: 3.4 MB

In [77]:
battery=vf[vf['Raw Data'].str.contains('Bat')]
battery

,Row Id,Sequence #,Server Time,Unit Time,Last Message Time,Latitude,Longitude,Driver Name,Event Name,Raw Event,...,ECU Engine Hours + Off,Engine Odometer,Engine Odometer + Off,ECU Engine Odometer,ECU Engine Odometer + Off,HDOP,VDOP,RSSI,Battery Level,Raw Data
7458,177812693717,NaN,2026/05/06 23:08:57,2026/05/06 22:15:59,2026/05/06 23:08:58,6.250899,-75.54848,NaN,Power Lost,CameraEvent.POWER_LOST,...,0,883.27,883.27,0,0,0.69,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."

In [78]:
vf['Event Name'].value_counts()

Event Name
AutoSnapshot             2027
Idle                     1776
Ignition On              1112
Ignition Off             1111
Travel Stop               873
Travel Start              870
Drive                     522
Power Lost                153
Main Power Disconnect     151
Main Power Connect        144
No Seatbelt                78
Hard Brake                  9
Stop Sign Violation         6
Drowsiness                  1
Rapid Acceleration          1
Name: count, dtype: int64

Ignition

In [80]:
vf_ignition=vf[vf['Event Name'].str.contains('Ignition Off')]
vf_ignition[['Event Name','Server Time','Unit Time','Last Message Time']]#.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_ignition_off.csv')

,Event Name,Server Time,Unit Time,Last Message Time
0,Ignition Off,2026/05/26 15:28:21,2026/05/26 15:28:10,2026/05/26 15:28:22
21,Ignition Off,2026/05/26 14:42:29,2026/05/26 14:42:15,2026/05/26 14:42:30
64,Ignition Off,2026/05/26 14:16:33,2026/05/26 14:16:16,2026/05/26 14:16:34
80,Ignition Off,2026/05/26 13:43:05,2026/05/26 13:41:40,2026/05/26 13:43:05
94,Ignition Off,2026/05/26 13:28:08,2026/05/26 13:27:46,2026/05/26 13:28:09
...,...,...,...,...
8785,Ignition Off,2026/05/01 06:08:56,2026/05/01 06:08:37,2026/05/01 06:08:57
8791,Ignition Off,2026/05/01 06:05:56,2026/05/01 06:05:44,2026/05/01 06:05:57
8796,Ignition Off,2026/05/01 06:00:58,2026/05/01 06:00:48,2026/05/01 06:00:58
8814,Ignition Off,2026/05/01 05:37:06,2026/05/01 05:36:46,2026/05/01 05:37:06
8819,Ignition Off,2026/05/01 05:22:26,2026/05/01 05:22:15,2026/05/01 05:22:27

Main Power Disconnect

In [91]:
vf_Main_Power_Disconnect=vf[vf['Event Name'].str.contains('Main Power Disconnect')]
vf_Main_Power_Disconnect[['Event Name','Server Time','Unit Time','Last Message Time']]#.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_MPD.csv')

,Event Name,Server Time,Unit Time,Last Message Time
4759,Main Power Disconnect,2026/05/13 16:28:07,2026/05/13 16:27:56,2026/05/13 16:28:08
4763,Main Power Disconnect,2026/05/13 16:24:10,2026/05/13 16:22:00,2026/05/13 16:24:13
4772,Main Power Disconnect,2026/05/13 16:01:13,2026/05/13 16:00:54,2026/05/13 16:01:13
5025,Main Power Disconnect,2026/05/13 09:28:36,2026/05/13 09:24:53,2026/05/13 09:28:36
5035,Main Power Disconnect,2026/05/13 09:15:25,2026/05/13 09:15:04,2026/05/13 09:15:25
...,...,...,...,...
8668,Main Power Disconnect,2026/05/01 10:27:29,2026/05/01 10:27:16,2026/05/01 10:27:30
8677,Main Power Disconnect,2026/05/01 10:08:49,2026/05/01 10:08:31,2026/05/01 10:08:49
8689,Main Power Disconnect,2026/05/01 09:13:19,2026/05/01 09:13:14,2026/05/01 09:13:19
8767,Main Power Disconnect,2026/05/01 06:59:19,2026/05/01 06:58:56,2026/05/01 06:59:19
8812,Main Power Disconnect,2026/05/01 05:53:27,2026/05/01 05:53:14,2026/05/01 05:53:28

Main Power Connect

In [92]:
vf_Main_Power_Connect=vf[vf['Event Name'].str.contains('Main Power Connect')]
vf_Main_Power_Connect[['Event Name','Server Time','Unit Time','Last Message Time']]#.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_MPC.csv')

,Event Name,Server Time,Unit Time,Last Message Time
4758,Main Power Connect,2026/05/13 16:41:37,2026/05/13 16:41:02,2026/05/13 16:41:37
4762,Main Power Connect,2026/05/13 16:28:06,2026/05/13 16:27:42,2026/05/13 16:28:06
4771,Main Power Connect,2026/05/13 16:23:45,2026/05/13 16:19:06,2026/05/13 16:23:45
5024,Main Power Connect,2026/05/13 09:29:37,2026/05/13 09:28:51,2026/05/13 09:29:37
5033,Main Power Connect,2026/05/13 09:28:34,2026/05/13 09:23:30,2026/05/13 09:28:34
...,...,...,...,...
8688,Main Power Connect,2026/05/01 10:06:10,2026/05/01 10:05:32,2026/05/01 10:06:10
8766,Main Power Connect,2026/05/01 07:42:00,2026/05/01 07:41:28,2026/05/01 07:42:01
8808,Main Power Connect,2026/05/01 05:53:47,2026/05/01 05:53:28,2026/05/01 05:53:47
8809,Main Power Connect,2026/05/01 05:58:48,2026/05/01 05:53:28,2026/05/01 05:58:48
8833,Main Power Connect,2026/05/01 05:05:06,2026/05/01 05:04:23,2026/05/01 05:05:06

Power Lost

In [93]:
vf_Power_Lost=vf[vf['Event Name'].str.contains('Power Lost')]
vf_Power_Lost[['Event Name','Server Time','Unit Time','Last Message Time']]#.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_Power_Lost.csv')

,Event Name,Server Time,Unit Time,Last Message Time
4760,Power Lost,2026/05/13 16:28:25,2026/05/13 16:27:53,2026/05/13 16:28:26
4764,Power Lost,2026/05/13 16:24:13,2026/05/13 16:21:57,2026/05/13 16:24:14
4773,Power Lost,2026/05/13 16:01:13,2026/05/13 16:00:51,2026/05/13 16:01:13
5026,Power Lost,2026/05/13 09:28:36,2026/05/13 09:24:53,2026/05/13 09:28:36
5036,Power Lost,2026/05/13 09:15:46,2026/05/13 09:15:01,2026/05/13 09:15:46
...,...,...,...,...
8669,Power Lost,2026/05/01 10:27:49,2026/05/01 10:27:13,2026/05/01 10:27:50
8678,Power Lost,2026/05/01 10:09:09,2026/05/01 10:08:27,2026/05/01 10:09:09
8690,Power Lost,2026/05/01 09:13:40,2026/05/01 09:13:11,2026/05/01 09:13:41
8768,Power Lost,2026/05/01 06:59:19,2026/05/01 06:27:55,2026/05/01 06:59:19
8813,Power Lost,2026/05/01 05:53:28,2026/05/01 05:53:11,2026/05/01 05:53:28

Restore Cable from Troubleshooting + Power Lost

In [94]:
ts=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_restore_cable.csv',sep=',')
ts.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Camera ESN      220 non-null    str
 1   Reason          220 non-null    str
 2   Powered By      219 non-null    str
 3   Created Time    220 non-null    str
 4   Power Off Time  111 non-null    str
 5   Recover Time    105 non-null    str
 6   Last Gps Data   220 non-null    str
dtypes: str(7)
memory usage: 12.2 KB

In [95]:
ts['Reason'].value_counts()

Reason
lostWhileParking    110
restoreCable        109
lostWhileDriving      1
Name: count, dtype: int64

In [90]:
ts[['Power Off Time','Reason','Created Time']]#.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\arepas\8B5221H4_restore_cable_events.csv')

             Power Off Time            Reason            Created Time
0                       NaN      restoreCable  May 13 2026 4:41:26 pm
1    May 13 2026 4:27:56 pm  lostWhileParking  May 13 2026 4:27:58 pm
2                       NaN      restoreCable  May 13 2026 4:27:57 pm
3    May 13 2026 4:22:00 pm  lostWhileParking  May 13 2026 4:22:02 pm
4                       NaN      restoreCable  May 13 2026 4:19:32 pm
..                      ...               ...                     ...
215  May 06 2026 9:43:25 am  lostWhileParking  May 06 2026 9:43:25 am
216                     NaN      restoreCable  May 06 2026 9:43:01 am
217  May 06 2026 9:41:29 am  lostWhileParking  May 06 2026 9:41:29 am
218                     NaN      restoreCable  May 06 2026 8:07:11 am
219  May 06 2026 7:51:03 am  lostWhileParking  May 06 2026 7:51:04 am

[220 rows x 3 columns]