In [2]:
import pandas as pd
import numpy as np

In [3]:
br=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\bomba_foods\Basic Report.csv',sep=',')
br.info()

<class 'pandas.DataFrame'>
RangeIndex: 42194 entries, 0 to 42193
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Textbox13       42194 non-null  str
 1   textbox4        42194 non-null  str
 2   textbox5        42194 non-null  str
 3   textbox6        42193 non-null  str
 4   DistanceDriven  42194 non-null  str
 5   textbox11       42193 non-null  str
 6   textbox2        42194 non-null  int64
 7   textbox7        42181 non-null  str
 8   textbox14       42194 non-null  int64
dtypes: int64(2), str(7)
memory usage: 2.9 MB

In [7]:
parked=br[br['textbox5'].str.contains('Estacionado')]
parked[['textbox4','textbox5','textbox11']].to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\bomba_foods\parked.csv')

In [10]:
vcx925=parked[parked['textbox4'].str.contains('VCX925')]
vcx925

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
35291,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:00:03 a.m.,0,Y,0
35292,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:05:03 a.m.,0,Y,0
35293,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:10:03 a.m.,0,Y,0
35294,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:15:03 a.m.,0,Y,0
35295,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:20:03 a.m.,0,Y,0
...,...,...,...,...,...,...,...,...,...
42131,Distance (kms),VCX925,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 8:28:40 a.m.,0,Y,0
42189,Distance (kms),VCX925,Estacionado,"Kr50 5-68, Cali, Valle Cauca Vca","0,00",17/07/2026 9:39:39 a.m.,0,Y,0
42190,Distance (kms),VCX925,Estacionado,"Kr50 5-73, Cali, Valle Cauca Vca","0,00",17/07/2026 9:44:39 a.m.,0,Y,0
42191,Distance (kms),VCX925,Estacionado,"Kr50 5a, Cali, Valle Cauca Vca","0,00",17/07/2026 9:49:39 a.m.,0,Y,0
42192,Distance (kms),VCX925,Estacionado,"Kr50 5a, Cali, Valle Cauca Vca","0,00",17/07/2026 9:54:39 a.m.,0,Y,0

In [18]:
QOR044=parked[parked['textbox4'].str.contains('QOR044')]
QOR044

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
34939,Distance (kms),QOR044,Estacionado,23 CN 46 46 # 3A-80 23 BN - 41 23c Norte42 23c...,"0,00",10/07/2026 12:12:29 p.m.,0,Y,0
34976,Distance (kms),QOR044,Estacionado,"Cl55a 29a-59, Cali, Valle Cauca Vca","0,00",10/07/2026 12:56:14 p.m.,0,Y,0
34994,Distance (kms),QOR044,Estacionado,"Kr8 38-11, Cali, Valle Cauca Vca","0,00",10/07/2026 2:23:14 p.m.,0,Y,0
35039,Distance (kms),QOR044,Estacionado,"South America, Florida, Valle del Cauca Florid...","0,00",10/07/2026 3:49:44 p.m.,0,Y,0
35102,Distance (kms),QOR044,Estacionado,"Cl56 29a-60, Cali, Valle Cauca, Colombia","0,00",10/07/2026 5:10:50 p.m.,0,Y,0
35113,Distance (kms),QOR044,Estacionado,"Cl. 55 #41d-15, Cali, Valle del Cauca, Colombi...","0,00",10/07/2026 5:38:44 p.m.,0,Y,0
35123,Distance (kms),QOR044,Estacionado,"Cl55a 29a-59, Cali, Valle Cauca Vca","0,00",10/07/2026 7:07:54 p.m.,0,Y,0
35128,Distance (kms),QOR044,Estacionado,"Kr32a 49a-58, Cali, Valle Cauca Vca","0,00",10/07/2026 9:40:21 p.m.,0,Y,0
35136,Distance (kms),QOR044,Estacionado,"Cl55a 30-47, Cali, Valle Cauca Vca","0,00",10/07/2026 9:45:37 p.m.,0,Y,0
35138,Distance (kms),QOR044,Estacionado,"Cl55a 29a-75, Cali, Valle Cauca Vca","0,00",10/07/2026 9:56:00 p.m.,1,Y,0
35141,Distance (kms),QOR044,Estacionado,"Cl56 29a-63, Cali, Valle Cauca Vca","0,00",10/07/2026 11:16:11 p.m.,1,Y,0
35148,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",11/07/2026 1:47:51 p.m.,0,Y,0
35172,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",11/07/2026 3:23:33 p.m.,0,Y,0
35173,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",11/07/2026 7:23:33 p.m.,0,Y,0
35178,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",11/07/2026 11:30:39 p.m.,0,Y,0
35179,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 3:30:38 a.m.,0,Y,0
35180,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 7:30:38 a.m.,0,Y,0
35181,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 11:30:38 a.m.,0,Y,0
35182,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 3:30:37 p.m.,0,Y,0
35183,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 7:30:37 p.m.,0,Y,0
35184,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",12/07/2026 11:30:37 p.m.,0,Y,0
35185,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 3:30:36 a.m.,0,Y,0
35186,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 7:30:36 a.m.,0,Y,0
35189,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 10:25:06 a.m.,0,Y,0
35190,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 2:25:05 p.m.,0,Y,0
35191,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 6:25:05 p.m.,0,Y,0
35192,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",13/07/2026 10:25:05 p.m.,0,Y,0
35193,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 2:25:04 a.m.,0,Y,0
35194,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 6:25:04 a.m.,0,Y,0
35197,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 10:13:28 a.m.,0,Y,0
35202,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 11:57:21 a.m.,0,Y,0
35212,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 1:42:04 p.m.,0,Y,0
35216,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 3:43:34 p.m.,0,Y,0
35217,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 7:43:33 p.m.,0,Y,0
35218,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",14/07/2026 11:43:33 p.m.,0,Y,0
35219,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 3:43:33 a.m.,0,Y,0
35224,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 5:41:42 a.m.,0,Y,0
35225,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 9:41:41 a.m.,0,Y,0
35228,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 9:58:36 a.m.,0,Y,0
35233,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 12:09:35 p.m.,0,Y,0
35264,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 1:37:04 p.m.,0,Y,0
35265,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 5:37:04 p.m.,0,Y,0
35266,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",15/07/2026 9:37:03 p.m.,0,Y,0
35267,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 1:37:03 a.m.,0,Y,0
35268,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:37:03 a.m.,0,Y,0
35269,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 9:37:02 a.m.,0,Y,0
35270,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 1:37:02 p.m.,0,Y,0
35281,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 3:32:02 p.m.,0,Y,0
35282,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 7:32:01 p.m.,0,Y,0
35283,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 11:32:01 p.m.,0,Y,0
35284,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 3:32:01 a.m.,0,Y,0
35285,Distance (kms),QOR044,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 7:32:00 a.m.,0,Y,0

In [12]:
QJK432=parked[parked['textbox4'].str.contains('QJK432')]
QJK432

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
28169,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:04:20 a.m.,0,Y,0
28170,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:09:20 a.m.,0,Y,0
28171,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:14:20 a.m.,0,Y,0
28172,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:19:20 a.m.,0,Y,0
28173,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:24:20 a.m.,0,Y,0
...,...,...,...,...,...,...,...,...,...
34825,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 5:23:15 a.m.,0,Y,0
34826,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 5:28:15 a.m.,0,Y,0
34827,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 5:33:15 a.m.,0,Y,0
34828,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 5:38:15 a.m.,0,Y,0
34829,Distance (kms),QJK432,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",17/07/2026 5:43:15 a.m.,0,Y,0

In [13]:
LLQ951=parked[parked['textbox4'].str.contains('LLQ951')]
LLQ951

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
16622,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",1/07/2026 5:08:18 p.m.,0,Y,0
16623,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",1/07/2026 5:13:18 p.m.,0,Y,0
16624,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",1/07/2026 5:18:18 p.m.,0,Y,0
16625,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",1/07/2026 5:23:18 p.m.,0,Y,0
16626,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",1/07/2026 5:28:18 p.m.,0,Y,0
...,...,...,...,...,...,...,...,...,...
28044,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",17/07/2026 2:26:38 a.m.,0,Y,0
28045,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",17/07/2026 2:31:38 a.m.,0,Y,0
28046,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",17/07/2026 2:36:38 a.m.,0,Y,0
28047,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",17/07/2026 2:41:38 a.m.,0,Y,0
28048,Distance (kms),LLQ951,Estacionado,"Via Principal, Cartagena, Bolivar Bol","0,00",17/07/2026 2:46:38 a.m.,0,Y,0

In [14]:
LLQ455=parked[parked['textbox4'].str.contains('LLQ455')]
LLQ455

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
7688,Distance (kms),LLQ455,Estacionado,"Cl9d 46-66, Cali, Valle Cauca, Colombia","0,00",1/07/2026 12:01:53 a.m.,0,Y,0
7689,Distance (kms),LLQ455,Estacionado,"Cl9d 46-60, Cali, Valle Cauca, Colombia","0,00",1/07/2026 12:06:53 a.m.,0,Y,0
7690,Distance (kms),LLQ455,Estacionado,"Cl. 9d #46-27 a 46-219, Cali, Cali, Valle del ...","0,00",1/07/2026 12:11:53 a.m.,0,Y,0
7691,Distance (kms),LLQ455,Estacionado,"Cl. 10 #48-7, Cali, Cali, Valle del Cauca, Col...","0,00",1/07/2026 12:16:53 a.m.,3,Y,0
7692,Distance (kms),LLQ455,Estacionado,"Cl. 10 #48-7, Cali, Cali, Valle del Cauca, Col...","0,00",1/07/2026 12:21:53 a.m.,0,Y,0
...,...,...,...,...,...,...,...,...,...
16174,Distance (kms),LLQ455,Estacionado,"Kr10e 57f-37, Manizales, Caldas, Colombia","0,00",17/07/2026 9:33:54 a.m.,0,Y,0
16175,Distance (kms),LLQ455,Estacionado,"Kr10e 57f-34, Manizales, Caldas Cal","0,00",17/07/2026 9:38:54 a.m.,0,Y,0
16176,Distance (kms),LLQ455,Estacionado,"Kr10e 57f-27, Manizales, Caldas, Colombia","0,00",17/07/2026 9:43:54 a.m.,0,Y,0
16177,Distance (kms),LLQ455,Estacionado,"Kr10e 57f-34, Manizales, Caldas Cal","0,00",17/07/2026 9:48:54 a.m.,0,Y,0
16178,Distance (kms),LLQ455,Estacionado,"Kr10e 57f-37, Manizales, Caldas, Colombia","0,00",17/07/2026 9:53:54 a.m.,0,Y,0

In [15]:
LLQ454=parked[parked['textbox4'].str.contains('LLQ454')]
LLQ454

,Textbox13,textbox4,textbox5,textbox6,DistanceDriven,textbox11,textbox2,textbox7,textbox14
2,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:04:38 a.m.,0,Y,0
3,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:09:38 a.m.,0,Y,0
4,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:14:38 a.m.,0,Y,0
5,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:19:38 a.m.,0,Y,0
6,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",1/07/2026 12:24:38 a.m.,0,Y,0
...,...,...,...,...,...,...,...,...,...
7427,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:36:02 p.m.,0,Y,0
7428,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:41:02 p.m.,0,Y,0
7429,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:46:02 p.m.,0,Y,0
7430,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:51:02 p.m.,0,Y,0
7431,Distance (kms),LLQ454,Estacionado,Carrera 36B Yumbo Valle del 760502,"0,00",16/07/2026 5:56:02 p.m.,0,Y,0

In [ ]:
# It does not report since June the 5th
FSV105=parked[parked['textbox4'].str.contains('FSV105')]
FSV105

Empty DataFrame
Columns: [Textbox13, textbox4, textbox5, textbox6, DistanceDriven, textbox11, textbox2, textbox7, textbox14]
Index: []