In [1]:
import pandas as pd
import numpy as np

In [2]:
ir_tdl795_0102_032026_ignition=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\idleReport_tdl795_0102_032026.csv',sep=',')
ir_tdl795_0102_032026_ignition.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unit                 2 non-null      str
 1   Time & Date (COT)    2 non-null      str
 2   Driver               0 non-null      float64
 3   Address              2 non-null      str
 4   Event                2 non-null      str
 5   Idle Time (minutes)  2 non-null      float64
dtypes: float64(2), str(4)
memory usage: 228.0 bytes

In [3]:
ir_tdl795_0102_032026_ignition

,Unit,Time & Date (COT),Driver,Address,Event,Idle Time (minutes)
0,TDL795,02/03/2026 05:26 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,13.57
1,TDL795,02/03/2026 05:49 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,59.48

In [4]:
ral_tdl795_0102_032026_tso=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\ralenti_tdl795_0102_032026.csv',sep=',')
ral_tdl795_0102_032026_tso.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   textbox12    0 non-null      float64
 1   textbox16    8 non-null      str
 2   EventTime    8 non-null      str
 3   Address      8 non-null      str
 4   EndLandmark  0 non-null      float64
 5   textbox25    8 non-null      str
 6   Driver       8 non-null      str
 7   textbox20    8 non-null      str
dtypes: float64(2), str(6)
memory usage: 644.0 bytes

In [5]:
ral_tdl795_0102_032026_tso[['textbox12','EventTime','textbox25']]

   textbox12               EventTime textbox25
0        NaN  2/03/2026 5:26:05 a.m.  00:12:33
1        NaN  2/03/2026 5:49:53 a.m.  00:58:28
2        NaN  2/03/2026 6:53:53 a.m.  00:04:54
3        NaN  2/03/2026 7:05:14 a.m.  00:00:22
4        NaN  2/03/2026 7:09:53 a.m.  00:00:02
5        NaN  2/03/2026 7:34:14 a.m.  00:01:01
6        NaN  2/03/2026 7:50:15 a.m.  00:03:32
7        NaN  2/03/2026 7:56:14 a.m.  00:13:01

New analysis:
I have exported again the reports on March 05, 2026 with an interval since March 02 to March 03.

In [6]:
ir_tdl795_0102_032026_ignition=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\idleReport_2026-03-05_ignition.csv',sep=',')
ir_tdl795_0102_032026_ignition.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unit                 6 non-null      str
 1   Time & Date (COT)    6 non-null      str
 2   Driver               0 non-null      float64
 3   Address              6 non-null      str
 4   Event                6 non-null      str
 5   Idle Time (minutes)  6 non-null      float64
dtypes: float64(2), str(4)
memory usage: 420.0 bytes

In [7]:
ir_tdl795_0102_032026_ignition

,Unit,Time & Date (COT),Driver,Address,Event,Idle Time (minutes)
0,TDL795,02/03/2026 05:26 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,13.57
1,TDL795,02/03/2026 05:49 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,59.48
2,TDL795,02/03/2026 07:05 AM,NaN,"2-210 Cl 24 E, Madrid, Cundinamarca, 250038",Idle,1.38
3,TDL795,02/03/2026 12:30 PM,NaN,"Cra. 9 Este, Soacha, Cundinamarca, 250054",Idle,3.07
4,TDL795,02/03/2026 13:40 PM,NaN,"3b29 Cra. 9, Soacha, Cundinamarca, 250051",Idle,2.92
5,TDL795,02/03/2026 16:29 PM,NaN,"# 70-25 Cra. 87c, Bogotá, D.C., Bogotá, D.C., ...",Idle,10.02

In [8]:
ral_tdl795_0102_032026_tso=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\Idles Report_2026_03_05_tso.csv',sep=',')
ral_tdl795_0102_032026_tso.info()

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   textbox12    0 non-null      float64
 1   textbox16    162 non-null    str
 2   EventTime    162 non-null    str
 3   Address      162 non-null    str
 4   EndLandmark  0 non-null      float64
 5   textbox25    162 non-null    str
 6   Driver       162 non-null    str
 7   textbox20    162 non-null    str
dtypes: float64(2), str(6)
memory usage: 10.3 KB

In [9]:
ral_tdl795_0102_032026_tso[['textbox20','EventTime','textbox25']]

,textbox20,EventTime,textbox25
0,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,2/03/2026 5:26:05 a.m.,00:12:33
1,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,2/03/2026 5:49:53 a.m.,00:58:28
2,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,2/03/2026 6:53:53 a.m.,00:04:54
3,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,2/03/2026 7:05:14 a.m.,00:00:22
4,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,2/03/2026 7:09:53 a.m.,00:00:02
...,...,...,...
157,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,3/03/2026 3:13:16 p.m.,00:01:00
158,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,3/03/2026 3:15:16 p.m.,00:02:00
159,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,3/03/2026 3:18:15 p.m.,00:01:01
160,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,3/03/2026 3:27:41 p.m.,00:02:36
161,# Stops: 162 - Max: 00:58:28 - Min: 00:00:02 -...,3/03/2026 3:38:15 p.m.,00:04:11