In [43]:
import pandas as pd
import numpy as np

In [ ]:
times_2331_03=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\timesheetReport_2026-04-15_1776270419593_fjfm79jmj.csv',sep=',')
utilization_2331_03=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\utilizationReport_2026-04-15_1776270510940_ir3ohz769.csv',sep=',')
ars_2331_03=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\Activity Report_v3.csv',sep=',')
times_2331_03['Unidad_aux']='NaN'
utilization_2331_03['Unidad_aux']='NaN'
ars_2331_03['Unidad_aux']='NaN'
ars_2331_03['Miles_float']=0.0
times_2331_03.info()
utilization_2331_03.info()
ars_2331_03.info()

In [45]:
raw_data=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\KYR910.csv',sep=',',encoding='latin1')
raw_datam=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\KYR910_columns.csv',sep=',',encoding='latin1')
raw_datam.rename(columns={'Unnamed: 1':'Message Type',
                                 'Unnamed: 2':'Protocole',
                                 'Unnamed: 3':'IMEI',
                                 'Unnamed: 4':'Serial',
                                 'Unnamed: 5':'Mileage',
                                 'Unnamed: 6':'Date',
                                 'Unnamed: 7':'Ignition',
                                 'Unnamed: 8':'Latitude',
                                 'Unnamed: 9':'Longitude',
                                 'Unnamed: 10':'Altitude',
                                 'Unnamed: 11':'External Power',
                                 'Unnamed: 12':'RPM',
                                 'Unnamed: 13':'Speed',
                                 'Unnamed: 14':'Satellite Number',
                                 'Unnamed: 15':'Azimuth',
                                 'Unnamed: 16':'Bettery level',
                                 },inplace=True)
raw_datam.info()
raw_datam.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\KYR910_columns_.csv')

<class 'pandas.DataFrame'>
RangeIndex: 2300 entries, 0 to 2299
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Message           2300 non-null   str
 1   Message Type      2300 non-null   str
 2   Protocole         2300 non-null   str
 3   IMEI              2300 non-null   str
 4   Serial            2300 non-null   str
 5   Mileage           2300 non-null   str
 6   Date              2300 non-null   str
 7   Ignition          2300 non-null   str
 8   Latitude          2300 non-null   str
 9   Longitude         2300 non-null   str
 10  Altitude          2300 non-null   str
 11  External Power    2170 non-null   str
 12  RPM               2170 non-null   str
 13  Speed             2040 non-null   str
 14  Satellite Number  2040 non-null   str
 15  Azimuth           2040 non-null   str
 16  Bettery level     2040 non-null   str
dtypes: str(17)
memory usage: 305.6 KB

In [46]:
cad_str_to_float=[]
for i in range(0, times_2331_03.shape[0]):
    times_2331_03.iloc[i,9]=times_2331_03.iloc[i,0]

for i in range(0, utilization_2331_03.shape[0]):
    utilization_2331_03.iloc[i,11]=utilization_2331_03.iloc[i,1]

for i in range(0, ars_2331_03.shape[0]):
    try:
        aux=ars_2331_03.iloc[i,4].replace('.','')
    except AttributeError as e:
        print("Troubles with report: ",ars_2331_03.iloc[i,2]," Unit:",ars_2331_03.iloc[i,1])
        ars_2331_03.iloc[i,4]='222222222'

Troubles with report:  25/03/2026 5:27 p.m.  Unit: Unit: KYR910
Troubles with report:  26/03/2026 1:34 p.m.  Unit: Unit: KYR910
Troubles with report:  27/03/2026 11:53 a.m.  Unit: Unit: KYR910
Troubles with report:  30/03/2026 7:13 a.m.  Unit: Unit: KYR910
Troubles with report:  30/03/2026 7:20 a.m.  Unit: Unit: KYR910
Troubles with report:  30/03/2026 9:48 a.m.  Unit: Unit: KYR910
Troubles with report:  30/03/2026 2:36 p.m.  Unit: Unit: KYR910
Troubles with report:  31/03/2026 10:37 a.m.  Unit: Unit: KYR910
Troubles with report:  31/03/2026 3:04 p.m.  Unit: Unit: KYR910

In [52]:
value_to_look=input('Type the short name to look in the CRM Raw Data (2026-03-25T11:23:34Z): ')
raw_datam_date=raw_datam[raw_datam['Date'].str.contains(value_to_look)]
raw_datam_date[['IMEI','Serial','Mileage','Date']]

,IMEI,Serial,Mileage,Date
459,"Imei:""869487064469157""",SerialNo:14894,Mileage:2865408,"Date:""2026-03-25T22:27:11Z"""
460,"Imei:""869487064469157""",SerialNo:14895,Mileage:2865446,"Date:""2026-03-25T22:27:25Z"""
461,"Imei:""869487064469157""",SerialNo:14896,Mileage:2865544,"Date:""2026-03-25T22:27:44Z"""
462,"Imei:""869487064469157""",SerialNo:14897,Mileage:2865710,"Date:""2026-03-25T22:28:10Z"""
463,"Imei:""869487064469157""",SerialNo:14898,Mileage:2865802,"Date:""2026-03-25T22:29:09Z"""
466,"Imei:""869487064469157""",SerialNo:14899,Mileage:2866264,"Date:""2026-03-25T22:29:48Z"""

In [ ]:
value_to_look=input('Type the short name to look in the CRM Raw Data (2026-03-25T11:23:34Z): ')
raw_datam_date=raw_datam[raw_datam['Date'].str.contains(value_to_look)]
raw_datam_date[['IMEI','Serial','Mileage','Date']]

In [53]:
value_to_look=input('Type the short name to look in the CRM Raw Data (2026-03-25T11:23:34Z): ')
raw_datam_date=raw_datam[raw_datam['Date'].str.contains(value_to_look)]
raw_datam_date[['IMEI','Serial','Mileage','Date']]

,IMEI,Serial,Mileage,Date
1083,"Imei:""869487064469157""",SerialNo:15367,Mileage:2947886,"Date:""2026-03-27T16:53:01Z"""
1084,"Imei:""869487064469157""",SerialNo:15368,Mileage:2948041,"Date:""2026-03-27T16:53:20Z"""
1085,"Imei:""869487064469157""",SerialNo:15369,Mileage:2948196,"Date:""2026-03-27T16:54:09Z"""
1086,"Imei:""869487064469157""",SerialNo:15370,Mileage:2948459,"Date:""2026-03-27T16:54:38Z"""
1087,"Imei:""869487064469157""",SerialNo:15371,Mileage:2949257,"Date:""2026-03-27T16:56:02Z"""
1088,"Imei:""869487064469157""",SerialNo:15372,Mileage:2949670,"Date:""2026-03-27T16:57:01Z"""
1089,"Imei:""869487064469157""",SerialNo:15373,Mileage:2950188,"Date:""2026-03-27T16:58:01Z"""
1090,"Imei:""869487064469157""",SerialNo:15374,Mileage:2950535,"Date:""2026-03-27T16:59:02Z"""

In [29]:
times_2331_03['Unidad'].value_counts()

Unidad
FSQ694    9
NOX568    9
KYR910    7
Name: count, dtype: int64

In [30]:
utilization_2331_03['Unidad'].value_counts()

Unidad
FSQ694    1
KYR910    1
NOX568    1
Name: count, dtype: int64

In [31]:
ars_2331_03['UnitName'].value_counts()

UnitName
Unit: FSQ694     438
Unit: KYR910     438
Unit: NOX568     340
Name: count, dtype: int64

In [32]:
ars_2331_03.groupby('UnitName').sum()

,GroupName,StartTime,MovingTimeSecs,MilesDriven,MaxSpeed,StopTime,textbox43,StopLengthSecs,ContactName,textbox45,...,textbox28,textbox29,textbox30,textbox32,MovingTimeSecs_1,MilesDriven_1,MaxSpeed_1,StopLengthSecs_1,Unidad_aux,Miles_float
UnitName,,,,,,,,,,,,,,,,,,,,,
Unit: FSQ694,0.0,23/03/2026 12:00 a.m.23/03/2026 1:39 p.m.23/03...,00h:00m:00s00h:00m:00s00h:00m:00s00h:00m:00s00...,"0,000,000,000,000,000,022,120,000,052,322,861,...",6305,23/03/2026 1:03:4.m.23/03/2026 1:39:3.m.23/03/...,Parked/IdleParked/IdleParked/IdleParked/IdlePa...,13h:59m:05s00h:39m:20s14h:10m:39s00h:05m:43s00...,"Cl145 145-29, Bogota, Cundinamarca, ColombiaCl...",CunCunCunCunCunBogotáBogotáBogotáBogotáCunBogo...,...,29h:04m:27s29h:04m:27s29h:04m:27s29h:04m:27s29...,"617,31617,31617,31617,31617,31617,31617,31617,...",19710,193h:30m:17s193h:30m:17s193h:30m:17s193h:30m:1...,109h:19m:03s109h:19m:03s109h:19m:03s109h:19m:0...,"1.686,081.686,081.686,081.686,081.686,081.686,...",21900,593h:04m:10s593h:04m:10s593h:04m:10s593h:04m:1...,NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNN...,0.0
Unit: KYR910,0.0,23/03/2026 12:00 a.m.24/03/2026 7:46 a.m.24/03...,00h:00m:00s00h:02m:06s00h:01m:00s00h:09m:26s00...,"0,000.000,104,252,820,000,000,001,140,790,000,...",5231,24/03/2026 7:45:3.m.24/03/2026 7:48:2.m.24/03/...,Parked/IdleIdleIdleIdleIgn OffParked/IdleParke...,31h:45m:38s00h:04m:00s00h:01m:33s00h:01m:00s00...,"Dg48ys 5q-84, Bogota, CundinamarcaKr10 49hs-81...",CunCunCunCunBogotáBogotáBogotáBogotáCunCundina...,...,56h:46m:03s56h:46m:03s56h:46m:03s56h:46m:03s56...,"363,18363,18363,18363,18363,18363,18363,18363,...",17520,198h:34m:21s198h:34m:21s198h:34m:21s198h:34m:2...,109h:19m:03s109h:19m:03s109h:19m:03s109h:19m:0...,"1.686,081.686,081.686,081.686,081.686,081.686,...",21900,593h:04m:10s593h:04m:10s593h:04m:10s593h:04m:1...,NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNN...,0.0
Unit: NOX568,0.0,23/03/2026 12:00 a.m.24/03/2026 6:25 a.m.24/03...,00h:00m:00s00h:05m:43s00h:10m:01s00h:01m:03s00...,"0,001,383,300,140,001,400,020,002,660,241,132,...",4130,24/03/2026 6:14:4.m.24/03/2026 6:30:4.m.24/03/...,Parked/IdleIdleIdleIdle/Ign OffParked/IdleIdle...,30h:24m:04s00h:00m:59s00h:00m:57s00h:11m:26s00...,"Cl. 47 Sur #1-1 a 1-15, Bogotá, Bogotá, Colomb...",BogotáCunCunCunCunCunCunCunCunCunCunCunCunCunC...,...,23h:28m:33s23h:28m:33s23h:28m:33s23h:28m:33s23...,"705,58705,58705,58705,58705,58705,58705,58705,...",17000,200h:59m:32s200h:59m:32s200h:59m:32s200h:59m:3...,109h:19m:03s109h:19m:03s109h:19m:03s109h:19m:0...,"1.686,081.686,081.686,081.686,081.686,081.686,...",17000,593h:04m:10s593h:04m:10s593h:04m:10s593h:04m:1...,NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNN...,0.0

In [33]:
df_book_table01=times_2331_03.groupby('Unidad').sum()
df_book_table01['Unidad_aux_']='NaN'
#df_book_table01.info()

for i in range(0,df_book_table01.shape[0]):
    df_book_table01.iloc[i,9]=df_book_table01.iloc[i,8][0:6]
df_book_table01.info()

<class 'pandas.DataFrame'>
Index: 3 entries, FSQ694 to NOX568
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Conductor               3 non-null      str
 1   Fecha                   3 non-null      str
 2   Ignición Encendido      3 non-null      str
 3   Ignición Apagado        3 non-null      str
 4   Dirección de Encendido  3 non-null      str
 5   Dirección de Apagado    3 non-null      str
 6   Tiempo                  3 non-null      str
 7   Distancia (km)          3 non-null      float64
 8   Unidad_aux              3 non-null      str
 9   Unidad_aux_             3 non-null      str
dtypes: float64(1), str(9)
memory usage: 264.0+ bytes

In [34]:
df_book_table01['Tiempo']

Unidad
FSQ694    1 hr, 10 min, 4 seg12 hr, 55 min, 53 seg12 hr,...
KYR910    10 hr, 35 min, 57 seg9 hr, 31 min, 14 seg10 hr...
NOX568    23 hr, 59 min, 59 seg12 hr, 25 min, 41 seg14 h...
Name: Tiempo, dtype: str

In [35]:
df_book_table02=utilization_2331_03.groupby('Unidad').sum()
df_book_table02.info()

<class 'pandas.DataFrame'>
Index: 3 entries, FSQ694 to NOX568
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Etiqueta                  3 non-null      str
 1   Conductor                 3 non-null      str
 2   Distancia (km)            3 non-null      float64
 3   Duración                  3 non-null      str
 4   Tiempo en Inactividad     3 non-null      str
 5   Tiempo de Parada          3 non-null      str
 6   Porcentaje en Movimiento  3 non-null      str
 7   Días Trabajados           3 non-null      int64
 8   Días Totales              3 non-null      int64
 9   Porcentaje de Días        3 non-null      str
 10  Unidad_aux                3 non-null      str
dtypes: float64(1), int64(2), str(8)
memory usage: 288.0+ bytes

In [36]:
num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[] 
list_field05=[] 
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Unidad_aux_'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='Unidad_aux'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]):
        #print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
        #print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])  
        if str(df_book_table01.iloc[i,position_table01][0:6])==str(df_book_table02.iloc[j,position_table02]):                                                                             
            list_field01.append(df_book_table01.iloc[i,9])
            list_field02.append(df_book_table01.iloc[i,7])
            list_field03.append(df_book_table02.iloc[j,2])
            list_field04.append(df_book_table01.iloc[i,6])
            list_field05.append(df_book_table02.iloc[j,3])
            #print("df_book_table01['Inside',i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            #print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Unidad']=list_field01
df_aux['Distancia (km) Times Report']=list_field02
df_aux['Distancia (km) Utilization']=list_field03
df_aux['Tiempo Times Report']=list_field04
df_aux['Tiempo Utilization']=list_field05
print("Cont= ",cont)
print(df_aux.info())
option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
if option_exp=="S":
    df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\coincidences.csv')                  #Edit
cont=0
print(df_aux)
option_exp=input("¿Desea generar un reporte de diferencias en formato csv S/N?\n")        
df_book_table02['ACTION']="Keep"
if option_exp=="S":
    print("Trabajando...")
    for i in range(0,num_filas_table01):
        for j in range(0,num_filas_table02):
            if str(df_book_table01.iloc[i,position_table01])==str(df_book_table02.iloc[j,position_table02]):
                df_book_table02.iloc[j,3]=np.nan
                print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
                print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
    #print(df_book_table02)
    df_book_table02.dropna(axis=0,inplace=True)
    #print(df_book_table02)
    df_book_table02.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\ort\diferences.csv')          #Edit

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
Index: 3 entries, FSQ694 to NOX568
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Conductor               3 non-null      str
 1   Fecha                   3 non-null      str
 2   Ignición Encendido      3 non-null      str
 3   Ignición Apagado        3 non-null      str
 4   Dirección de Encendido  3 non-null      str
 5   Dirección de Apagado    3 non-null      str
 6   Tiempo                  3 non-null      str
 7   Distancia (km)          3 non-null      float64
 8   Unidad_aux              3 non-null      str
 9   Unidad_aux_             3 non-null      str
dtypes: float64(1), str(9)
memory usage: 372.0+ bytes
None

Tabla 2:
<class 'pandas.DataFrame'>
Index: 3 entries, FSQ694 to NOX568
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Etiqueta                  3 non-null      str
 1   Conductor                 3 non-null      str
 2   Distancia (km)            3 non-null      float64
 3   Duración                  3 non-null      str
 4   Tiempo en Inactividad     3 non-null      str
 5   Tiempo de Parada          3 non-null      str
 6   Porcentaje en Movimiento  3 non-null      str
 7   Días Trabajados           3 non-null      int64
 8   Días Totales              3 non-null      int64
 9   Porcentaje de Días        3 non-null      str
 10  Unidad_aux                3 non-null      str
dtypes: float64(1), int64(2), str(8)
memory usage: 288.0+ bytes
None

Atributo de la tabla1:  9
Atributo de la tabla2:  10

Trabajando...
Cont=  3
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unidad                       3 non-null      str
 1   Distancia (km) Times Report  3 non-null      float64
 2   Distancia (km) Utilization   3 non-null      float64
 3   Tiempo Times Report          3 non-null      str
 4   Tiempo Utilization           3 non-null      str
dtypes: float64(2), str(3)
memory usage: 252.0 bytes
None
   Unidad  Distancia (km) Times Report  Distancia (km) Utilization  \
0  FSQ694                       617.33                      616.89
1  KYR910                       343.10                      397.43
2  NOX568                       697.98                      706.11

                                 Tiempo Times Report  \
0  1 hr, 10 min, 4 seg12 hr, 55 min, 53 seg12 hr,...
1  10 hr, 35 min, 57 seg9 hr, 31 min, 14 seg10 hr...
2  23 hr, 59 min, 59 seg12 hr, 25 min, 41 seg14 h...

              Tiempo Utilization
0  1 días, 15 hr, 49 min, 32 seg
1          19 hr, 45 min, 29 seg
2    1 días, 2 hr, 4 min, 53 seg
Trabajando...
df_book_table01[i,position_table01]:  FSQ694  = df_book_table02[j,position_table02]:  FSQ694
df_book_table01[i,position_table01]:  KYR910  = df_book_table02[j,position_table02]:  KYR910
df_book_table01[i,position_table01]:  NOX568  = df_book_table02[j,position_table02]:  NOX568