In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\sena\GESTION DE DATOS EN MODELOS DE INTELIGENCIA ARTIFICIAL\customer_satisfaction_data_1.csv')
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            15 non-null     str
 1   Age                   15 non-null     int64
 2   PlanType              15 non-null     str
 3   MonthlyBill           11 non-null     float64
 4   HoursWatched_Last30d  15 non-null     float64
 5   SignupDate            15 non-null     str
 6   LastSupportTicket     15 non-null     str
 7   SatisfactionScore     15 non-null     int64
dtypes: float64(2), int64(2), str(4)
memory usage: 1.1 KB

In [3]:
ds.head(15)

,CustomerID,Age,PlanType,MonthlyBill,HoursWatched_Last30d,SignupDate,LastSupportTicket,SatisfactionScore
0,8432-XYZ,34,Premium,25.99,120.5,2022-08-15,"No issues, everything works great.",5
1,1256-ABC,45,Estándar,NaN,80.2,2021-11-30,My recommendations are not relevant.,3
2,9874-JKL,120,Básico,9.99,45.1,2023-01-10,Video keeps buffering on my TV.,2
3,3321-MNO,28,premium,25.99,210.8,2022-04-22,How do I change my password?,4
4,5647-PQR,0,Estándar,15.99,95.0,2024-02-05,I can't log in. The system gives me an error.,1
5,7890-STU,52,PREM,NaN,150.3,2021-07-20,The new interface is confusing.,2
6,1111-VWX,25,Básico,9.99,60.7,2023-09-01,Can I download shows to watch offline?,4
7,2222-YZA,39,Estándar,15.99,75.4,2022-11-10,The app crashed on my phone. I had to restart it.,3
8,4455-BCD,150,Premium,NaN,180.0,2020-06-18,Playback error code 500. Please fix.,1
9,6789-EFG,41,premium,25.99,195.2,2022-03-12,I love the new documentary series!,5
10,8899-HIJ,22,Básico,9.99,55.9,2024-01-20,"Billing question, I think I was overcharged.",3
11,9900-KLM,37,Estándar,15.99,110.0,2023-05-18,Audio is out of sync on season 2 of 'The Wande...,2
12,3456-NOP,68,Premium,25.99,99.8,2021-07-07,Your competitor has a better price.,2
13,7654-QRS,19,Básico,NaN,70.1,2023-10-05,Cannot find the show my friend recommended.,4
14,2345-TUV,31,PREM,25.99,140.6,2022-02-01,The search function needs improvement.,3

Integridad y validez: Hay edades de 150 y 120, que inidicarían una anomalía.
Completitud: Hay campos NaN que deben ser diligenciados.
Uniformidad: En la columna Plan Type no hay valores uniformes, se mezclan mayúsculas con minúsculas y en algunos casos la palabra está incompleta.

Estos inconvenientes generarían confusión y fallas en el código de procesamiento al intentar usar valores numéricos nulos.

Se deben reemplazar las edades atípicas por valores promedio.
Los valores NaN deben ser eliminados.
Se deben manejar solamente los valores Premium, Estándar y Básico para Plan Type.

In [6]:
for i in range(0,ds.shape[0]):
    if ds.iloc[i,2]!='Básico' and ds.iloc[i,2]!='Estándar':
        ds.iloc[i,2]='Premium'

ds['PlanType'].value_counts()

PlanType
Premium     7
Estándar    4
Básico      4
Name: count, dtype: int64

In [8]:
ds.dropna(inplace=True)
ds

,CustomerID,Age,PlanType,MonthlyBill,HoursWatched_Last30d,SignupDate,LastSupportTicket,SatisfactionScore
0,8432-XYZ,34,Premium,25.99,120.5,2022-08-15,"No issues, everything works great.",5
2,9874-JKL,120,Básico,9.99,45.1,2023-01-10,Video keeps buffering on my TV.,2
3,3321-MNO,28,Premium,25.99,210.8,2022-04-22,How do I change my password?,4
4,5647-PQR,0,Estándar,15.99,95.0,2024-02-05,I can't log in. The system gives me an error.,1
6,1111-VWX,25,Básico,9.99,60.7,2023-09-01,Can I download shows to watch offline?,4
7,2222-YZA,39,Estándar,15.99,75.4,2022-11-10,The app crashed on my phone. I had to restart it.,3
9,6789-EFG,41,Premium,25.99,195.2,2022-03-12,I love the new documentary series!,5
10,8899-HIJ,22,Básico,9.99,55.9,2024-01-20,"Billing question, I think I was overcharged.",3
11,9900-KLM,37,Estándar,15.99,110.0,2023-05-18,Audio is out of sync on season 2 of 'The Wande...,2
12,3456-NOP,68,Premium,25.99,99.8,2021-07-07,Your competitor has a better price.,2
14,2345-TUV,31,Premium,25.99,140.6,2022-02-01,The search function needs improvement.,3

In [9]:
ds.describe()

              Age  MonthlyBill  HoursWatched_Last30d  SatisfactionScore
count   11.000000    11.000000             11.000000          11.000000
mean    40.454545    18.899091            109.909091           3.090909
std     30.988268     7.175717             54.370681           1.300350
min      0.000000     9.990000             45.100000           1.000000
25%     26.500000    12.990000             68.050000           2.000000
50%     34.000000    15.990000             99.800000           3.000000
75%     40.000000    25.990000            130.550000           4.000000
max    120.000000    25.990000            210.800000           5.000000

In [11]:
for i in range(0,ds.shape[0]):
    if ds.iloc[i,1]>40:
        ds.iloc[i,1]=40

ds

,CustomerID,Age,PlanType,MonthlyBill,HoursWatched_Last30d,SignupDate,LastSupportTicket,SatisfactionScore
0,8432-XYZ,34,Premium,25.99,120.5,2022-08-15,"No issues, everything works great.",5
2,9874-JKL,40,Básico,9.99,45.1,2023-01-10,Video keeps buffering on my TV.,2
3,3321-MNO,28,Premium,25.99,210.8,2022-04-22,How do I change my password?,4
4,5647-PQR,0,Estándar,15.99,95.0,2024-02-05,I can't log in. The system gives me an error.,1
6,1111-VWX,25,Básico,9.99,60.7,2023-09-01,Can I download shows to watch offline?,4
7,2222-YZA,39,Estándar,15.99,75.4,2022-11-10,The app crashed on my phone. I had to restart it.,3
9,6789-EFG,40,Premium,25.99,195.2,2022-03-12,I love the new documentary series!,5
10,8899-HIJ,22,Básico,9.99,55.9,2024-01-20,"Billing question, I think I was overcharged.",3
11,9900-KLM,37,Estándar,15.99,110.0,2023-05-18,Audio is out of sync on season 2 of 'The Wande...,2
12,3456-NOP,40,Premium,25.99,99.8,2021-07-07,Your competitor has a better price.,2
14,2345-TUV,31,Premium,25.99,140.6,2022-02-01,The search function needs improvement.,3

Variables numéricas finales: Age, SatisfactionScore y HoursWatched_Last30d.