In [1]:
import pandas as pd
import numpy as np

In [2]:
#ars in Kilometers
ars_12022026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\Activity Report Summarized_es_2026-03-18.csv',sep=',')
ars_12022026['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars_12022026.shape[0]):
    aux=ars_12022026.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)

ars_12022026['MilesDriven_dec']=cad_str_to_float
ars_12022026['MilesDriven_dec']

ars_12022026.info()

for i in range(0,ars_12022026.shape[0]):
    ars_12022026.iloc[i,18]=float(ars_12022026.iloc[i,19])*0.621371
    #print(ars_12022026.iloc[i,19],ars_12022026.iloc[i,18])

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox20             43 non-null     str
 12  Textbox21             43 non-null     str
 13  Textbox24             43 non-null     str
 14  Textbox25             43 non-null     str
 15  Textbox26             43 non-null     str
 16  Textbox27             43 non-null     str
 17  Textbox28             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [3]:
#ur in miles
ur_12022026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\utilizationReport_2026-03-18.csv',sep=',')
ur_12022026.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             2 non-null      str
 3   Distance (mi)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB

In [4]:
value_to_look=input('Type the short name to look in the Activity Report Summarized: ')
ars_12022026_sn=ars_12022026[ars_12022026['UnitName1'].str.contains(value_to_look)]
ars_12022026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']]

      UnitName1 MilesDriven  MilesDriven_in_Miles
9        LUL144      636,69            395.620702
10  LUL144 AIR2        0,00              0.000000

In [5]:
value_to_look=input('Type the short name to look in the Utilization Report: ')
ur_12022026_sn=ur_12022026[ur_12022026['Unit'].str.contains(value_to_look)]
ur_12022026_sn[['Unit','Distance (mi)',]]

     Unit  Distance (mi)
6  LUL144         395.13

In [6]:
value_to_look=input('Type the short name to look for: ')
ur_12022026_sn=ur_12022026[ur_12022026['Unit'].str.contains(value_to_look)]
ars_12022026_sn=ars_12022026[ars_12022026['UnitName1'].str.contains(value_to_look)]
print("Short name typed: ", value_to_look)
print("\n")
print('Actividades (Sumarizado) from TSO:')
print(ars_12022026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']])
print("\n")
print('Utilization Report from Ignition:')
print(ur_12022026_sn[['Unit','Distance (mi)',]])

Short name typed:  LUL144


Actividades (Sumarizado) from TSO:
      UnitName1 MilesDriven  MilesDriven_in_Miles
9        LUL144      636,69            395.620702
10  LUL144 AIR2        0,00              0.000000


Utilization Report from Ignition:
     Unit  Distance (mi)
6  LUL144         395.13

SOUDAL
UU067H
SXX967

In [84]:
#ars in Kilometers
ars_18032026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\Activity Report Summarized_es_2026_03_18_soudal.csv',sep=',')
ars_18032026['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars_18032026.shape[0]):
    aux=ars_18032026.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)

ars_18032026['MilesDriven_dec']=cad_str_to_float
ars_18032026['MilesDriven_dec']

ars_18032026.info()

for i in range(0,ars_18032026.shape[0]):
    ars_18032026.iloc[i,18]=float(ars_18032026.iloc[i,19])*0.621371
    #print(ars_12022026.iloc[i,19],ars_12022026.iloc[i,18])

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                16 non-null     str
 2   UnitName1             16 non-null     str
 3   MaxSpeed              16 non-null     int64
 4   MilesDriven           16 non-null     str
 5   TravelTimeSecs        16 non-null     str
 6   Textbox3              16 non-null     str
 7   IdleTimeSecs          16 non-null     str
 8   Textbox6              16 non-null     str
 9   IdleTimeSecs2         16 non-null     str
 10  Textbox11             16 non-null     str
 11  Textbox20             16 non-null     str
 12  Textbox21             16 non-null     str
 13  Textbox24             16 non-null     str
 14  Textbox25             16 non-null     str
 15  Textbox26             16 non-null     str
 16  Textbox27             16 non-null     str
 17  Textbox28             16 non-null     str
 18  MilesDriven_in_Miles  16 non-null     float64
 19  MilesDriven_dec       16 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 2.6 KB

Test 27-03-2026 16:36

In [11]:
#Activity Reports Summary
#ars in Kilometers
ars=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\Activity Report Summarized 270320261636.csv',sep=',')
ars['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars.shape[0]):
    aux=ars.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)

ars['MilesDriven_dec']=cad_str_to_float

ars.info()

for i in range(0,ars.shape[0]):
    ars.iloc[i,18]=float(ars.iloc[i,19])*0.621371
    #print(ars_12022026.iloc[i,19],ars_12022026.iloc[i,18])

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [12]:
ur=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\utilizationReport_2026-03-27.csv',sep=',')
ur.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             3 non-null      str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB

In [13]:
df_book_table01=ur
df_book_table02=ars
df_book_table01.fillna('0',inplace=True)
df_book_table02.fillna(0,inplace=True)
df_book_table01.info()
df_book_table02.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [15]:
num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[]
list_field05=[]       
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Unit'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='UnitName1'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]):
        #print(df_book_table01.iloc[i,position_table01],df_book_table02.iloc[j,position_table02]) 
        if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:                                                                             
            list_field01.append(df_book_table01.iloc[i,1])
            list_field02.append(df_book_table01.iloc[i,3])
            list_field03.append(df_book_table02.iloc[j,4])
            list_field04.append(df_book_table01.iloc[i,4])
            list_field05.append(df_book_table02.iloc[j,5])
            print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Unit']=list_field01
df_aux['PM Distance']=list_field02
df_aux['TSO Distance']=list_field03
df_aux['PM Duration']=list_field04
df_aux['TSO TravelTimeSecs']=list_field05
print("Cont= ",cont)
print(df_aux.info())
option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
if option_exp=="S":
    df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\coincidences.csv')                  #Edit
cont=0
option_exp=input("¿Desea generar un reporte de diferencias en formato csv S/N?\n")        
df_book_table02['ACTION']="Keep"
if option_exp=="S":
    print("Trabajando...")
    for i in range(0,num_filas_table01):
        for j in range(0,num_filas_table02):
            if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:
                df_book_table02.iloc[j,3]=np.nan
                #print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
                #print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
    #print(df_book_table02)
    df_book_table02.dropna(axis=0,inplace=True)
    #print(df_book_table02)
    df_book_table02.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\differences.csv')          #Edit

print(df_aux)

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB
None

Tabla 2:
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB
None

Atributo de la tabla1:  1
Atributo de la tabla2:  2

Trabajando...
df_book_table01[i,position_table01]:  LUL144  = df_book_table02[j,position_table02]:  LUL144
df_book_table01[i,position_table01]:  NUW693  = df_book_table02[j,position_table02]:  NUW693
df_book_table01[i,position_table01]:  QJX175  = df_book_table02[j,position_table02]:  QJX175
df_book_table01[i,position_table01]:  IBZ301  = df_book_table02[j,position_table02]:  IBZ301
df_book_table01[i,position_table01]:  SXZ756  = df_book_table02[j,position_table02]:  SXZ756
df_book_table01[i,position_table01]:  TDL796  = df_book_table02[j,position_table02]:  TDL796
df_book_table01[i,position_table01]:  LQK053  = df_book_table02[j,position_table02]:  LQK053
df_book_table01[i,position_table01]:  LQK054  = df_book_table02[j,position_table02]:  LQK054
df_book_table01[i,position_table01]:  NOY423  = df_book_table02[j,position_table02]:  NOY423
df_book_table01[i,position_table01]:  NOY424  = df_book_table02[j,position_table02]:  NOY424
df_book_table01[i,position_table01]:  SMR391  = df_book_table02[j,position_table02]:  SMR391
df_book_table01[i,position_table01]:  TDL795  = df_book_table02[j,position_table02]:  TDL795
df_book_table01[i,position_table01]:  WFL149  = df_book_table02[j,position_table02]:  WFL149
df_book_table01[i,position_table01]:  SMR198  = df_book_table02[j,position_table02]:  SMR198
df_book_table01[i,position_table01]:  SXY625  = df_book_table02[j,position_table02]:  SXY625
df_book_table01[i,position_table01]:  TDL797  = df_book_table02[j,position_table02]:  TDL797
Cont=  16
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unit                16 non-null     str
 1   PM Distance         16 non-null     float64
 2   TSO Distance        16 non-null     str
 3   PM Duration         16 non-null     str
 4   TSO TravelTimeSecs  16 non-null     str
dtypes: float64(1), str(4)
memory usage: 772.0 bytes
None
      Unit  PM Distance TSO Distance           PM Duration TSO TravelTimeSecs
0   LUL144        27.27        27,76  1 hr, 11 min, 52 sec          1H:0M:50S
1   NUW693       348.74       339,06   5 hr, 8 min, 49 sec         7H:47M:15S
2   QJX175       319.63       297,17   7 hr, 8 min, 52 sec          5H:45M:8S
3   IBZ301        35.20        36,11   2 hr, 0 min, 50 sec         1H:58M:26S
4   SXZ756         0.00         0,00          0 min, 0 sec          0H:0M:19S
5   TDL796       252.77       253,70  3 hr, 16 min, 14 sec         5H:24M:44S
6   LQK053        77.80        66,50  5 hr, 57 min, 28 sec         3H:32M:14S
7   LQK054        57.70        56,55  7 hr, 25 min, 18 sec          3H:18M:9S
8   NOY423       102.71       107,05  6 hr, 28 min, 11 sec          4H:5M:47S
9   NOY424       106.37       107,23  2 hr, 32 min, 46 sec         4H:38M:35S
10  SMR391        63.12        63,97   7 hr, 4 min, 12 sec         3H:35M:37S
11  TDL795        74.75        75,14   3 hr, 2 min, 14 sec          3H:50M:6S
12  WFL149        37.86        35,89          0 min, 0 sec         1H:20M:58S
13  SMR198         0.00        41,15          0 min, 0 sec          2H:7M:27S
14  SXY625        37.20        37,74  2 hr, 35 min, 56 sec           2H:5M:6S
15  TDL797       105.97       109,85   1 hr, 9 min, 56 sec         5H:12M:51S

Test March 30, 2026. Reports since 27-03-2026 to 29-03-2026.

In [7]:
#Activity Reports Summary
#ars in Kilometers
ars=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\Activity Report Summarized_2703_2903.csv',sep=',')
ars['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars.shape[0]):
    aux=ars.iloc[i,4].replace('.','')
    ars.iloc[i,4]=aux
    aux=ars.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)    
    
#print(cad_str_to_float)

ars['MilesDriven_dec']=cad_str_to_float

ars.info()
for i in range(0,ars.shape[0]):
    ars.iloc[i,18]=float(ars.iloc[i,19])*0.621371

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [8]:
ur=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\utilizationReport_2703_2903.csv',sep=',')
ur.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             3 non-null      str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB

In [9]:
df_book_table01=ur
df_book_table02=ars
df_book_table01.fillna('0',inplace=True)
df_book_table02.fillna(0,inplace=True)
df_book_table01.info()
df_book_table02.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [10]:
num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[]
list_field05=[]       
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Unit'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='UnitName1'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]):
        #print(df_book_table01.iloc[i,position_table01],df_book_table02.iloc[j,position_table02]) 
        if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:                                                                             
            list_field01.append(df_book_table01.iloc[i,1])
            list_field02.append(df_book_table01.iloc[i,3])
            list_field03.append(df_book_table02.iloc[j,4])
            list_field04.append(df_book_table01.iloc[i,4])
            list_field05.append(df_book_table02.iloc[j,5])
            print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Unit']=list_field01
df_aux['PM Distance']=list_field02
df_aux['TSO Distance']=list_field03
df_aux['PM Duration']=list_field04
df_aux['TSO TravelTimeSecs']=list_field05
print("Cont= ",cont)
print(df_aux.info())
option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
if option_exp=="S":
    df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\coincidences_30032026.csv')                  #Edit
cont=0
option_exp=input("¿Desea generar un reporte de diferencias en formato csv S/N?\n")        
df_book_table02['ACTION']="Keep"
if option_exp=="S":
    print("Trabajando...")
    for i in range(0,num_filas_table01):
        for j in range(0,num_filas_table02):
            if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:
                df_book_table02.iloc[j,3]=np.nan
                #print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
                #print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
    #print(df_book_table02)
    df_book_table02.dropna(axis=0,inplace=True)
    #print(df_book_table02)
    df_book_table02.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\differences_30032026.csv')          #Edit

print(df_aux)

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     str
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB
None

Tabla 2:
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB
None

Atributo de la tabla1:  1
Atributo de la tabla2:  2

Trabajando...
df_book_table01[i,position_table01]:  LUL144  = df_book_table02[j,position_table02]:  LUL144
df_book_table01[i,position_table01]:  NUW693  = df_book_table02[j,position_table02]:  NUW693
df_book_table01[i,position_table01]:  QJX175  = df_book_table02[j,position_table02]:  QJX175
df_book_table01[i,position_table01]:  IBZ301  = df_book_table02[j,position_table02]:  IBZ301
df_book_table01[i,position_table01]:  SXZ756  = df_book_table02[j,position_table02]:  SXZ756
df_book_table01[i,position_table01]:  TDL796  = df_book_table02[j,position_table02]:  TDL796
df_book_table01[i,position_table01]:  LQK053  = df_book_table02[j,position_table02]:  LQK053
df_book_table01[i,position_table01]:  LQK054  = df_book_table02[j,position_table02]:  LQK054
df_book_table01[i,position_table01]:  NOY423  = df_book_table02[j,position_table02]:  NOY423
df_book_table01[i,position_table01]:  NOY424  = df_book_table02[j,position_table02]:  NOY424
df_book_table01[i,position_table01]:  SMR391  = df_book_table02[j,position_table02]:  SMR391
df_book_table01[i,position_table01]:  TDL795  = df_book_table02[j,position_table02]:  TDL795
df_book_table01[i,position_table01]:  WFL149  = df_book_table02[j,position_table02]:  WFL149
df_book_table01[i,position_table01]:  SMR198  = df_book_table02[j,position_table02]:  SMR198
df_book_table01[i,position_table01]:  SXY625  = df_book_table02[j,position_table02]:  SXY625
df_book_table01[i,position_table01]:  TDL797  = df_book_table02[j,position_table02]:  TDL797
Cont=  16
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unit                16 non-null     str
 1   PM Distance         16 non-null     float64
 2   TSO Distance        16 non-null     str
 3   PM Duration         16 non-null     str
 4   TSO TravelTimeSecs  16 non-null     str
dtypes: float64(1), str(4)
memory usage: 772.0 bytes
None
      Unit  PM Distance TSO Distance                   PM Duration  \
0   LUL144       160.47       160,76          7 hr, 22 min, 11 sec
1   NUW693       573.67       565,22         14 hr, 22 min, 49 sec
2   QJX175      1064.89      1050,02    1 days, 9 hr, 1 min, 2 sec
3   IBZ301        56.30        56,31          2 hr, 40 min, 48 sec
4   SXZ756       174.32       174,32          4 hr, 42 min, 47 sec
5   TDL796       479.94       480,50         11 hr, 11 min, 20 sec
6   LQK053       104.99        76,78           7 hr, 1 min, 54 sec
7   LQK054       275.86       272,57          19 hr, 5 min, 12 sec
8   NOY423       313.31       313,29          24 hr, 9 min, 47 sec
9   NOY424       428.42       428,42  1 days, 4 hr, 59 min, 23 sec
10  SMR391       478.58       479,21  1 days, 6 hr, 22 min, 50 sec
11  TDL795       345.28       345,41         24 hr, 41 min, 54 sec
12  WFL149       121.70       119,72           5 hr, 53 min, 2 sec
13  SMR198       336.34       214,14          8 hr, 30 min, 56 sec
14  SXY625       202.90       202,65          9 hr, 14 min, 12 sec
15  TDL797       272.05       271,58         20 hr, 27 min, 57 sec

   TSO TravelTimeSecs
0            5H:4M:0S
1          14H:12M:6S
2       1D:1H:24M:30S
3          2H:31M:57S
4          3H:58M:18S
5          9H:14M:26S
6            4H:0M:0S
7         12H:35M:40S
8          11H:48M:9S
9         16H:15M:20S
10        17H:25M:29S
11          14H:4M:7S
12          4H:26M:0S
13         10H:3M:31S
14          7H:26M:6S
15        13H:17M:34S

Test March 30, 2026. Reports since 18-04-2026 to 19-04-2026.

In [11]:
#Activity Reports Summary
#ars in Kilometers
ars=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\Activity Report Summarized 1819_042026.csv',sep=',')
ars['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars.shape[0]):
    aux=ars.iloc[i,4].replace('.','')
    ars.iloc[i,4]=aux
    aux=ars.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)    
    
#print(cad_str_to_float)

ars['MilesDriven_dec']=cad_str_to_float

ars.info()
for i in range(0,ars.shape[0]):
    ars.iloc[i,18]=float(ars.iloc[i,19])*0.621371

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [12]:
ur=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\utilizationReport_1819_042026.csv',sep=',')
ur.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             0 non-null      float64
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(2), int64(2), str(7)
memory usage: 2.1 KB

In [14]:
df_book_table01=ur
df_book_table02=ars
df_book_table01.fillna(0,inplace=True)
df_book_table02.fillna(0,inplace=True)
df_book_table01.info()
df_book_table02.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     float64
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(2), int64(2), str(7)
memory usage: 2.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [15]:
num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[]
list_field05=[]       
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Unit'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='UnitName1'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]):
        #print(df_book_table01.iloc[i,position_table01],df_book_table02.iloc[j,position_table02]) 
        if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:                                                                             
            list_field01.append(df_book_table01.iloc[i,1])
            list_field02.append(df_book_table01.iloc[i,3])
            list_field03.append(df_book_table02.iloc[j,4])
            list_field04.append(df_book_table01.iloc[i,4])
            list_field05.append(df_book_table02.iloc[j,5])
            print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Unit']=list_field01
df_aux['PM Distance']=list_field02
df_aux['TSO Distance']=list_field03
df_aux['PM Duration']=list_field04
df_aux['TSO TravelTimeSecs']=list_field05
print("Cont= ",cont)
print(df_aux.info())
option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
if option_exp=="S":
    df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\coincidences_30032026.csv')                  #Edit
cont=0
option_exp=input("¿Desea generar un reporte de diferencias en formato csv S/N?\n")        
df_book_table02['ACTION']="Keep"
if option_exp=="S":
    print("Trabajando...")
    for i in range(0,num_filas_table01):
        for j in range(0,num_filas_table02):
            if df_book_table01.iloc[i,position_table01]==df_book_table02.iloc[j,position_table02]:
                df_book_table02.iloc[j,3]=np.nan
                #print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
                #print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
    #print(df_book_table02)
    df_book_table02.dropna(axis=0,inplace=True)
    #print(df_book_table02)
    df_book_table02.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\differences_30032026.csv')          #Edit

print(df_aux)

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             23 non-null     float64
 3   Distance (km)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(2), int64(2), str(7)
memory usage: 2.1 KB
None

Tabla 2:
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             43 non-null     float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox15             43 non-null     str
 12  Textbox16             43 non-null     str
 13  Textbox17             43 non-null     str
 14  Textbox18             43 non-null     str
 15  Textbox19             43 non-null     str
 16  Textbox22             43 non-null     str
 17  Textbox23             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB
None

Atributo de la tabla1:  1
Atributo de la tabla2:  2

Trabajando...
df_book_table01[i,position_table01]:  LUL144  = df_book_table02[j,position_table02]:  LUL144
df_book_table01[i,position_table01]:  NUW693  = df_book_table02[j,position_table02]:  NUW693
df_book_table01[i,position_table01]:  QJX175  = df_book_table02[j,position_table02]:  QJX175
df_book_table01[i,position_table01]:  IBZ301  = df_book_table02[j,position_table02]:  IBZ301
df_book_table01[i,position_table01]:  SXZ756  = df_book_table02[j,position_table02]:  SXZ756
df_book_table01[i,position_table01]:  TDL796  = df_book_table02[j,position_table02]:  TDL796
df_book_table01[i,position_table01]:  LQK053  = df_book_table02[j,position_table02]:  LQK053
df_book_table01[i,position_table01]:  LQK054  = df_book_table02[j,position_table02]:  LQK054
df_book_table01[i,position_table01]:  NOY423  = df_book_table02[j,position_table02]:  NOY423
df_book_table01[i,position_table01]:  NOY424  = df_book_table02[j,position_table02]:  NOY424
df_book_table01[i,position_table01]:  SMR391  = df_book_table02[j,position_table02]:  SMR391
df_book_table01[i,position_table01]:  TDL795  = df_book_table02[j,position_table02]:  TDL795
df_book_table01[i,position_table01]:  WFL149  = df_book_table02[j,position_table02]:  WFL149
df_book_table01[i,position_table01]:  SMR198  = df_book_table02[j,position_table02]:  SMR198
df_book_table01[i,position_table01]:  SXY625  = df_book_table02[j,position_table02]:  SXY625
df_book_table01[i,position_table01]:  TDL797  = df_book_table02[j,position_table02]:  TDL797
Cont=  16
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unit                16 non-null     str
 1   PM Distance         16 non-null     float64
 2   TSO Distance        16 non-null     str
 3   PM Duration         16 non-null     str
 4   TSO TravelTimeSecs  16 non-null     str
dtypes: float64(1), str(4)
memory usage: 772.0 bytes
None
Trabajando...
      Unit  PM Distance TSO Distance            PM Duration TSO TravelTimeSecs
0   LUL144       479.69       479,81  11 hr, 21 min, 16 sec        11H:26M:21S
1   NUW693       459.29       457,09  10 hr, 54 min, 12 sec        10H:43M:51S
2   QJX175       564.18       481,58  14 hr, 52 min, 15 sec         13H:2M:45S
3   IBZ301         0.00         0,00           0 min, 0 sec           0H:0M:0S
4   SXZ756         0.00         0,00           0 min, 0 sec           0H:0M:0S
5   TDL796         0.00         0,00           0 min, 0 sec           0H:0M:0S
6   LQK053        66.74        36,19    1 hr, 5 min, 51 sec          1H:6M:20S
7   LQK054         0.00         0,00           0 min, 0 sec           0H:0M:0S
8   NOY423        12.12        12,12          25 min, 1 sec         0H:25M:29S
9   NOY424         0.00         0,00           0 min, 0 sec           0H:0M:0S
10  SMR391        14.76        14,79          28 min, 4 sec         0H:29M:23S
11  TDL795         0.00         0,00           0 min, 0 sec           0H:0M:0S
12  WFL149         0.00         0,00           0 min, 0 sec           0H:0M:0S
13  SMR198         0.00         0,00           0 min, 0 sec           0H:0M:0S
14  SXY625        71.16        71,08   3 hr, 46 min, 45 sec         3H:48M:12S
15  TDL797         0.00         0,00           0 min, 0 sec           0H:0M:0S

In [ ]:
br=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\brahman\Basic Report_1819_042026.csv',sep=',')
br.info()

<class 'pandas.DataFrame'>
RangeIndex: 8870 entries, 0 to 8869
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Textbox13       8870 non-null   str
 1   textbox4        8870 non-null   str
 2   textbox5        8870 non-null   str
 3   textbox6        8869 non-null   str
 4   DistanceDriven  8870 non-null   str
 5   textbox11       8869 non-null   str
 6   textbox2        8870 non-null   int64
 7   textbox7        8808 non-null   str
 8   textbox14       8870 non-null   int64
dtypes: int64(2), str(7)
memory usage: 623.8 KB

In [29]:
unit=input("Type the unit to analyze: ")
print("Analyzing ",unit)
unit_events=br[br['textbox4'].str.contains(unit)]
unit_events['textbox5'].value_counts()

Analyzing  LQK053

textbox5
Drive               101
Parked               60
Idle - Stop          50
Ignition ON          36
Ignition OFF         36
Towing/Drifting?     23
End Report            2
Start Report          1
Name: count, dtype: int64

In [30]:
unit=input("Type the unit to analyze: ")
print("Analyzing ",unit)
unit_events=br[br['textbox4'].str.contains(unit)]
unit_events['textbox5'].value_counts()

Analyzing  LUL144

textbox5
Drive           861
Idle - Stop     240
Parked           26
Ignition OFF     22
Ignition ON      21
End Report        2
Start Report      1
Name: count, dtype: int64

In [31]:
unit=input("Type the unit to analyze: ")
print("Analyzing ",unit)
unit_events=br[br['textbox4'].str.contains(unit)]
unit_events['textbox5'].value_counts()

Analyzing  QJX175

textbox5
Drive           1115
Idle - Stop      491
Ignition OFF      24
Ignition ON       24
Parked            19
End Report         3
Start Report       1
Name: count, dtype: int64