In [1]:
import pandas as pd
import numpy as np

In [ ]:
ir_tdl795_0102_032026_ignition=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\idleReport_tdl795_0102_032026.csv',sep=',')
ir_tdl795_0102_032026_ignition

,Unit,Time & Date (COT),Driver,Address,Event,Idle Time (minutes)
0,TDL795,02/03/2026 05:26 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,13.57
1,TDL795,02/03/2026 05:49 AM,NaN,Avda Troncal de Occidente # 18 - 76 Parque Ind...,Idle,59.48

In [6]:
ral_tdl795_0102_032026_tso=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\ralenti_tdl795_0102_032026.csv',sep=',')
ral_tdl795_0102_032026_tso.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   textbox12    0 non-null      float64
 1   textbox16    8 non-null      str
 2   EventTime    8 non-null      str
 3   Address      8 non-null      str
 4   EndLandmark  0 non-null      float64
 5   textbox25    8 non-null      str
 6   Driver       8 non-null      str
 7   textbox20    8 non-null      str
dtypes: float64(2), str(6)
memory usage: 644.0 bytes

In [11]:
ral_tdl795_0102_032026_tso[['textbox12','EventTime','textbox25']]

   textbox12               EventTime textbox25
0        NaN  2/03/2026 5:26:05 a.m.  00:12:33
1        NaN  2/03/2026 5:49:53 a.m.  00:58:28
2        NaN  2/03/2026 6:53:53 a.m.  00:04:54
3        NaN  2/03/2026 7:05:14 a.m.  00:00:22
4        NaN  2/03/2026 7:09:53 a.m.  00:00:02
5        NaN  2/03/2026 7:34:14 a.m.  00:01:01
6        NaN  2/03/2026 7:50:15 a.m.  00:03:32
7        NaN  2/03/2026 7:56:14 a.m.  00:13:01