In [ ]:
import pandas as pd
import numpy as np

In [2]:
#ars in Kilometers
ars_12022026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\Activity Report Summarized_es_2026-03-18.csv',sep=',')
ars_12022026['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars_12022026.shape[0]):
    aux=ars_12022026.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)

ars_12022026['MilesDriven_dec']=cad_str_to_float
ars_12022026['MilesDriven_dec']

ars_12022026.info()

for i in range(0,ars_12022026.shape[0]):
    ars_12022026.iloc[i,18]=float(ars_12022026.iloc[i,19])*0.621371
    #print(ars_12022026.iloc[i,19],ars_12022026.iloc[i,18])

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                43 non-null     str
 2   UnitName1             43 non-null     str
 3   MaxSpeed              43 non-null     int64
 4   MilesDriven           43 non-null     str
 5   TravelTimeSecs        43 non-null     str
 6   Textbox3              43 non-null     str
 7   IdleTimeSecs          43 non-null     str
 8   Textbox6              43 non-null     str
 9   IdleTimeSecs2         43 non-null     str
 10  Textbox11             43 non-null     str
 11  Textbox20             43 non-null     str
 12  Textbox21             43 non-null     str
 13  Textbox24             43 non-null     str
 14  Textbox25             43 non-null     str
 15  Textbox26             43 non-null     str
 16  Textbox27             43 non-null     str
 17  Textbox28             43 non-null     str
 18  MilesDriven_in_Miles  43 non-null     float64
 19  MilesDriven_dec       43 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 6.8 KB

In [3]:
#ur in miles
ur_12022026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\utilizationReport_2026-03-18.csv',sep=',')
ur_12022026.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             2 non-null      str
 3   Distance (mi)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB

In [4]:
value_to_look=input('Type the short name to look for: ')
ars_12022026_sn=ars_12022026[ars_12022026['UnitName1'].str.contains(value_to_look)]
ars_12022026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']]

     UnitName1 MilesDriven  MilesDriven_in_Miles
5       LQK053      192,06            119.340514
6  LQK053 AIR2        0,00              0.000000

In [5]:
value_to_look=input('Type the short name to look for: ')
ur_12022026_sn=ur_12022026[ur_12022026['Unit'].str.contains(value_to_look)]
ur_12022026_sn[['Unit','Distance (mi)',]]

      Unit  Distance (mi)
13  LQK053         135.42

In [6]:
value_to_look=input('Type the short name to look for: ')
ur_12022026_sn=ur_12022026[ur_12022026['Unit'].str.contains(value_to_look)]
ars_12022026_sn=ars_12022026[ars_12022026['UnitName1'].str.contains(value_to_look)]
print("Short name typed: ", value_to_look)
print("\n")
print('Actividades (Sumarizado) from TSO:')
print(ars_12022026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']])
print("\n")
print('Utilization Report from Ignition:')
print(ur_12022026_sn[['Unit','Distance (mi)',]])

Short name typed:  LQK053


Actividades (Sumarizado) from TSO:
     UnitName1 MilesDriven  MilesDriven_in_Miles
5       LQK053      192,06            119.340514
6  LQK053 AIR2        0,00              0.000000


Utilization Report from Ignition:
      Unit  Distance (mi)
13  LQK053         135.42

SOUDAL
UU067H
SXX967

In [15]:
#ars in Kilometers
ars_18032026=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\brahman\Activity Report Summarized_es_2026_03_18_soudal.csv',sep=',')
ars_18032026['MilesDriven_in_Miles']=0.0
cad_str_to_float=[]

for i in range(0,ars_18032026.shape[0]):
    aux=ars_18032026.iloc[i,4].replace(',','.')
    cad_str_to_float.append(aux)

ars_18032026['MilesDriven_dec']=cad_str_to_float
ars_18032026['MilesDriven_dec']

ars_18032026.info()

for i in range(0,ars_18032026.shape[0]):
    ars_18032026.iloc[i,18]=float(ars_18032026.iloc[i,19])*0.621371
    #print(ars_12022026.iloc[i,19],ars_12022026.iloc[i,18])

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GroupName             0 non-null      float64
 1   UnitID                16 non-null     str
 2   UnitName1             16 non-null     str
 3   MaxSpeed              16 non-null     int64
 4   MilesDriven           16 non-null     str
 5   TravelTimeSecs        16 non-null     str
 6   Textbox3              16 non-null     str
 7   IdleTimeSecs          16 non-null     str
 8   Textbox6              16 non-null     str
 9   IdleTimeSecs2         16 non-null     str
 10  Textbox11             16 non-null     str
 11  Textbox20             16 non-null     str
 12  Textbox21             16 non-null     str
 13  Textbox24             16 non-null     str
 14  Textbox25             16 non-null     str
 15  Textbox26             16 non-null     str
 16  Textbox27             16 non-null     str
 17  Textbox28             16 non-null     str
 18  MilesDriven_in_Miles  16 non-null     float64
 19  MilesDriven_dec       16 non-null     str
dtypes: float64(2), int64(1), str(17)
memory usage: 2.6 KB

In [ ]:
ur_18032026=pd.read_csv(r'',sep=',')
ur_18032026.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tag                23 non-null     str
 1   Unit               23 non-null     str
 2   Driver             2 non-null      str
 3   Distance (mi)      23 non-null     float64
 4   Duration           23 non-null     str
 5   Idle Time          23 non-null     str
 6   Stop Time          23 non-null     str
 7   Moving Percentage  23 non-null     str
 8   Days Worked        23 non-null     int64
 9   Days Total         23 non-null     int64
 10  Days Percentage    23 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 KB

In [17]:
value_to_look=input('Type the short name to look for: ')
ars_18032026_sn=ars_18032026[ars_18032026['UnitName1'].str.contains(value_to_look)]
ars_18032026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']]

   UnitName1 MilesDriven  MilesDriven_in_Miles
15    UU067H       23,98             14.900477

In [ ]:
value_to_look=input('Type the short name to look for: ')
ur_12022026_sn=ur_12022026[ur_12022026['Unit'].str.contains(value_to_look)]
ur_12022026_sn[['Unit','Distance (mi)',]]

In [ ]:
value_to_look=input('Type the short name to look for: ')
ur_18032026_sn=ur_18032026[ur_18032026['Unit'].str.contains(value_to_look)]
ars_18032026_sn=ars_18032026[ars_18032026['UnitName1'].str.contains(value_to_look)]
print("Short name typed: ", value_to_look)
print("\n")
print('Actividades (Sumarizado) from TSO:')
print(ars_18032026_sn[['UnitName1','MilesDriven','MilesDriven_in_Miles']])
print("\n")
print('Utilization Report from Ignition:')
print(ur_18032026_sn[['Unit','Distance (mi)',]])