In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
#from yellowbrick.cluster import SilhouetteVisualizer

In [2]:
cu=pd.read_excel(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\CustomerUnits.xlsx')
cu['Unit Type'].value_counts()

c:\Users\Jose.Hurtado\Documents\Zonar_projects\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Unit Type
Queclink GV55W                                     212
VidFleet 4K                                         40
Topfly PioneerX                                     39
VidFleet AIR2                                       15
CalAmp 2630 - CINTERION GSM - LMU30H30BT3-G1000      1
CalAmp 2630 - GEMALTO HSPA -LMU26H3001-JAM01         1
Name: count, dtype: int64

In [3]:
cu.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               308 non-null    int64
 1   Owner                    0 non-null      float64
 2   Unit ID                  308 non-null    str
 3   Unit                     308 non-null    str
 4   Peripherals              0 non-null      float64
 5   Billing Period           0 non-null      float64
 6   Reporting Status         0 non-null      float64
 7   Show Until               0 non-null      float64
 8   Billing Group            5 non-null      str
 9   Last Event Date          308 non-null    str
 10  Monthly Fee              308 non-null    float64
 11  Bill To                  14 non-null     str
 12  Assigned To              308 non-null    str
 13  Linked Mode              0 non-null      float64
 14  Paired GPS               0 non-null      float64
 15  Paired Camera            0 non-null      float64
 16  Billable                 308 non-null    str
 17  RMA                      308 non-null    str
 18  Unit Type                308 non-null    str
 19  IMEI                     308 non-null    str
 20  Serial Number            308 non-null    str
 21  Phone Number             308 non-null    str
 22  UnitCarrierID            308 non-null    int64
 23  Carrier                  300 non-null    str
 24  SIM #                    308 non-null    str
 25  VIN                      1 non-null      str
 26  License Plate            12 non-null     str
 27  Static IP                0 non-null      float64
 28  Event                    308 non-null    str
 29  Last Contact On          308 non-null    str
 30  Min                      308 non-null    int64
 31  Server IP                308 non-null    str
 32  Server Port              308 non-null    int64
 33  Last Event Address       308 non-null    str
 34  Modem                    300 non-null    str
 35  Inv #                    308 non-null    str
 36  Status                   308 non-null    str
 37  Last Service Paid Until  308 non-null    str
 38  Service Paid Until       308 non-null    str
 39  Assigned to Company      308 non-null    str
 40  IFTA                     308 non-null    str
 41  History Months           308 non-null    int64
 42  Comments                 0 non-null      float64
 43  Warranty Expires         308 non-null    str
 44  Script                   2 non-null      str
 45  JBOX Profile             0 non-null      float64
 46  Contract Type            0 non-null      float64
 47  Subscription             0 non-null      float64
 48  Firmware                 1 non-null      str
dtypes: float64(14), int64(5), str(30)
memory usage: 118.0 KB

In [4]:
cu_failure=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\units_reported.csv',sep=',')
cu_failure.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Short_name  16 non-null     str
dtypes: str(1)
memory usage: 260.0 bytes

In [5]:
df_book_table01=cu_failure
df_book_table02=cu

num_filas_table01=int(df_book_table01.shape[0])
num_filas_table02=int(df_book_table02.shape[0])       
cont=0
df_aux=pd.DataFrame()        
list_field01=[]
list_field02=[]
list_field03=[]
list_field04=[]       
#print("df_book_table01[8,0]: ",df_book_table01.iloc[8,0]) #UnitsByDealer.csv_r.csv
#print("df_book_table02[8,5]: ",df_book_table02.iloc[8,5]) #6MB.        
print("\nInformación de las tablas: ")
print("\nTabla 1:")
print(df_book_table01.info())
print("\nTabla 2:")
print(df_book_table02.info())
attribute_name_table01='Short_name'#Digitar el índice de la tabla 1.#input("\nDigita el atributo a comparar de la tabla 1: ")
attribute_name_table02='Unit'#Digitar el índice de la tabla 2.#input("Digita el atribito a comparar de la tabla 2: ")
position_table01=int(df_book_table01.columns.get_loc(attribute_name_table01))
position_table02=int(df_book_table02.columns.get_loc(attribute_name_table02))
print("\nAtributo de la tabla1: ",position_table01)
print("Atributo de la tabla2: ",position_table02,"\n")
print("Trabajando...")                          
for i in range(0,num_filas_table01):
    for j in range(0,num_filas_table02):
        #if str(df_book_table01.iloc[i,5])==str(df_book_table02.iloc[j,3]): 
        if (df_book_table01.iloc[i,position_table01])==(df_book_table02.iloc[j,position_table02]):                                                                             
            list_field01.append(df_book_table01.iloc[i,0])
            list_field02.append(df_book_table02.iloc[j,19])
            list_field03.append(df_book_table02.iloc[j,18])
            list_field04.append(df_book_table02.iloc[j,29])
            print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
            print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
            cont=cont+1
df_aux['Short_name']=list_field01
df_aux['IMEI']=list_field02
df_aux['Unit type']=list_field03
df_aux['Last Contact On']=list_field04
print("Cont= ",cont)
print(df_aux.info())
option_exp=input("\n¿Desea generar un reporte de coincidencias en formato csv S/N?\n")
if option_exp=="S":
    df_aux.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\units_failing.csv')                  #Edit
cont=0
option_exp=input("¿Desea generar un reporte de diferencias en formato csv S/N?\n")        
df_book_table02['ACTION']="Keep"
if option_exp=="S":
    print("Trabajando...")
    for i in range(0,num_filas_table01):
        for j in range(0,num_filas_table02):
            if str(df_book_table01.iloc[i,position_table01])==str(df_book_table02.iloc[j,position_table02]):
                df_book_table02.iloc[j,3]=np.nan
                print("df_book_table01[i,position_table01]: ",df_book_table01.iloc[i,position_table01]," = ",end="")
                print("df_book_table02[j,position_table02]: ",df_book_table02.iloc[j,position_table02])               
    #print(df_book_table02)
    df_book_table02.dropna(axis=0,inplace=True)
    print(df_book_table02)
    df_book_table02.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\dif_units_failing.csv')          #Edit

Información de las tablas:

Tabla 1:
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Short_name  16 non-null     str
dtypes: str(1)
memory usage: 260.0 bytes
None

Tabla 2:
<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               308 non-null    int64
 1   Owner                    0 non-null      float64
 2   Unit ID                  308 non-null    str
 3   Unit                     308 non-null    str
 4   Peripherals              0 non-null      float64
 5   Billing Period           0 non-null      float64
 6   Reporting Status         0 non-null      float64
 7   Show Until               0 non-null      float64
 8   Billing Group            5 non-null      str
 9   Last Event Date          308 non-null    str
 10  Monthly Fee              308 non-null    float64
 11  Bill To                  14 non-null     str
 12  Assigned To              308 non-null    str
 13  Linked Mode              0 non-null      float64
 14  Paired GPS               0 non-null      float64
 15  Paired Camera            0 non-null      float64
 16  Billable                 308 non-null    str
 17  RMA                      308 non-null    str
 18  Unit Type                308 non-null    str
 19  IMEI                     308 non-null    str
 20  Serial Number            308 non-null    str
 21  Phone Number             308 non-null    str
 22  UnitCarrierID            308 non-null    int64
 23  Carrier                  300 non-null    str
 24  SIM #                    308 non-null    str
 25  VIN                      1 non-null      str
 26  License Plate            12 non-null     str
 27  Static IP                0 non-null      float64
 28  Event                    308 non-null    str
 29  Last Contact On          308 non-null    str
 30  Min                      308 non-null    int64
 31  Server IP                308 non-null    str
 32  Server Port              308 non-null    int64
 33  Last Event Address       308 non-null    str
 34  Modem                    300 non-null    str
 35  Inv #                    308 non-null    str
 36  Status                   308 non-null    str
 37  Last Service Paid Until  308 non-null    str
 38  Service Paid Until       308 non-null    str
 39  Assigned to Company      308 non-null    str
 40  IFTA                     308 non-null    str
 41  History Months           308 non-null    int64
 42  Comments                 0 non-null      float64
 43  Warranty Expires         308 non-null    str
 44  Script                   2 non-null      str
 45  JBOX Profile             0 non-null      float64
 46  Contract Type            0 non-null      float64
 47  Subscription             0 non-null      float64
 48  Firmware                 1 non-null      str
dtypes: float64(14), int64(5), str(30)
memory usage: 118.0 KB
None

Atributo de la tabla1:  0
Atributo de la tabla2:  3

Trabajando...
df_book_table01[i,position_table01]:  CGQ270  = df_book_table02[j,position_table02]:  CGQ270
df_book_table01[i,position_table01]:  EQY796  = df_book_table02[j,position_table02]:  EQY796
df_book_table01[i,position_table01]:  EQZ327  = df_book_table02[j,position_table02]:  EQZ327
df_book_table01[i,position_table01]:  EQZ329  = df_book_table02[j,position_table02]:  EQZ329
df_book_table01[i,position_table01]:  EQZ330  = df_book_table02[j,position_table02]:  EQZ330
df_book_table01[i,position_table01]:  EQZ355  = df_book_table02[j,position_table02]:  EQZ355
df_book_table01[i,position_table01]:  ERK700  = df_book_table02[j,position_table02]:  ERK700
df_book_table01[i,position_table01]:  KOK936  = df_book_table02[j,position_table02]:  KOK936
df_book_table01[i,position_table01]:  EQY796  = df_book_table02[j,position_table02]:  EQY796
df_book_table01[i,position_table01]:  EQZ330  = df_book_table02[j,position_table02]:  EQZ330
df_book_table01[i,position_table01]:  EQZ355  = df_book_table02[j,position_table02]:  EQZ355
df_book_table01[i,position_table01]:  ERK700  = df_book_table02[j,position_table02]:  ERK700
df_book_table01[i,position_table01]:  PRZ609  = df_book_table02[j,position_table02]:  PRZ609
df_book_table01[i,position_table01]:  PRZ982  = df_book_table02[j,position_table02]:  PRZ982
df_book_table01[i,position_table01]:  SOO657  = df_book_table02[j,position_table02]:  SOO657
df_book_table01[i,position_table01]:  WNM396  = df_book_table02[j,position_table02]:  WNM396
Cont=  16
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Short_name       16 non-null     str
 1   IMEI             16 non-null     str
 2   Unit type        16 non-null     str
 3   Last Contact On  16 non-null     str
dtypes: str(4)
memory usage: 644.0 bytes
None
Trabajando...
df_book_table01[i,position_table01]:  CGQ270  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  EQY796  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  EQZ327  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  EQZ329  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  EQZ330  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  EQZ355  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  ERK700  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  KOK936  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  PRZ609  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  PRZ982  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  SOO657  = df_book_table02[j,position_table02]:  nan
df_book_table01[i,position_table01]:  WNM396  = df_book_table02[j,position_table02]:  nan
Empty DataFrame
Columns: [Unnamed: 0, Owner, Unit ID, Unit, Peripherals, Billing Period, Reporting Status, Show Until, Billing Group, Last Event Date, Monthly Fee, Bill To, Assigned To, Linked Mode, Paired GPS, Paired Camera, Billable, RMA, Unit Type, IMEI, Serial Number, Phone Number, UnitCarrierID, Carrier, SIM #, VIN, License Plate, Static IP, Event, Last Contact On, Min, Server IP, Server Port, Last Event Address, Modem, Inv #, Status, Last Service Paid Until, Service Paid Until, Assigned to Company, IFTA, History Months, Comments, Warranty Expires, Script, JBOX Profile, Contract Type, Subscription, Firmware, ACTION]
Index: []

[0 rows x 50 columns]

In [6]:
units_failing=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\units_failing.csv',sep=',')
units_failing.drop("Unnamed: 0",axis=1)

   Short_name             IMEI        Unit type          Last Contact On
0      CGQ270  869487061675582  Topfly PioneerX  2026-07-07 16:39:56.103
1      EQY796  868574042784996   Queclink GV55W  2026-07-07 16:05:05.263
2      EQZ327  868574042848049   Queclink GV55W  2026-07-07 16:15:36.420
3      EQZ329  868574042900006   Queclink GV55W  2026-07-07 16:39:55.220
4      EQZ330  868574042888151   Queclink GV55W  2026-07-07 15:43:00.090
5      EQZ355  868574042898549   Queclink GV55W  2026-07-06 13:11:56.157
6      ERK700  868574042918081   Queclink GV55W  2026-07-07 16:35:23.353
7      KOK936  868574042788351   Queclink GV55W  2026-07-07 16:39:54.673
8      EQY796  868574042784996   Queclink GV55W  2026-07-07 16:05:05.263
9      EQZ330  868574042888151   Queclink GV55W  2026-07-07 15:43:00.090
10     EQZ355  868574042898549   Queclink GV55W  2026-07-06 13:11:56.157
11     ERK700  868574042918081   Queclink GV55W  2026-07-07 16:35:23.353
12     PRZ609  869487064415689  Topfly PioneerX  2026-07-07 16:39:34.893
13     PRZ982  868574042894688   Queclink GV55W  2026-07-07 16:29:42.280
14     SOO657  868574042913991   Queclink GV55W  2026-07-07 16:20:49.533
15     WNM396  868574042784426   Queclink GV55W  2026-07-07 15:51:38.167

In [7]:
units_failing_processed=units_failing.drop_duplicates('Short_name')
units_failing_processed

,Unnamed: 0,Short_name,IMEI,Unit type,Last Contact On
0,0,CGQ270,869487061675582,Topfly PioneerX,2026-07-07 16:39:56.103
1,1,EQY796,868574042784996,Queclink GV55W,2026-07-07 16:05:05.263
2,2,EQZ327,868574042848049,Queclink GV55W,2026-07-07 16:15:36.420
3,3,EQZ329,868574042900006,Queclink GV55W,2026-07-07 16:39:55.220
4,4,EQZ330,868574042888151,Queclink GV55W,2026-07-07 15:43:00.090
5,5,EQZ355,868574042898549,Queclink GV55W,2026-07-06 13:11:56.157
6,6,ERK700,868574042918081,Queclink GV55W,2026-07-07 16:35:23.353
7,7,KOK936,868574042788351,Queclink GV55W,2026-07-07 16:39:54.673
12,12,PRZ609,869487064415689,Topfly PioneerX,2026-07-07 16:39:34.893
13,13,PRZ982,868574042894688,Queclink GV55W,2026-07-07 16:29:42.280
14,14,SOO657,868574042913991,Queclink GV55W,2026-07-07 16:20:49.533
15,15,WNM396,868574042784426,Queclink GV55W,2026-07-07 15:51:38.167

In [8]:
units_failing_processed['Unit type'].value_counts()

Unit type
Queclink GV55W     10
Topfly PioneerX     2
Name: count, dtype: int64

In [9]:
print('Queclink: ', (10/12)*100,'%', 'TopFly: ',(2/12)*100,'%')

Queclink:  83.33333333333334 % TopFly:  16.666666666666664 %

In [10]:
ar0=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_cgq270.csv',sep=',')
ar1=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_eqy796.csv',sep=',')
ar2=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_eqz327.csv',sep=',')
ar3=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_eqz329.csv',sep=',')
ar4=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_eqz330.csv',sep=',')
ar5=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_eqz355.csv',sep=',')
ar6=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_erk700.csv',sep=',')
ar7=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_kok936.csv',sep=',')
ar8=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_prz609.csv',sep=',')
ar9=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_prz982.csv',sep=',')
ar10=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_soo657.csv',sep=',')
ar11=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\ar_wnm396.csv',sep=',')

ar_total=pd.concat([ar0,ar1,ar2,ar3,ar4,ar5,ar6,ar7,ar8,ar9,ar10,ar11])

ar_total.info()

<class 'pandas.DataFrame'>
Index: 202727 entries, 0 to 14982
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   UnitID        202727 non-null  str
 1   EventCode     202727 non-null  str
 2   UTC_DateTime  202727 non-null  str
 3   Address       202727 non-null  str
 4   Latitude      202727 non-null  str
 5   Longitude     202727 non-null  str
dtypes: str(6)
memory usage: 10.8 MB

In [11]:
ar_total['lat_float']=0.0
ar_total['lon_float']=0.0
aux_lat='NaN'
aux_lon='Nan'

ar_total.info()

lat_str_to_float=[]
lon_str_to_float=[]

for i in range(0,ar_total.shape[0]):    
    aux_lat=ar_total.iloc[i,4].replace(',','.')
    lat_str_to_float.append(aux_lat) 
    #print(aux_lat, ar_total.iloc[i,4])   
    aux_lon=ar_total.iloc[i,5].replace(',','.')
    lon_str_to_float.append(aux_lon)
    #print(aux_lon, ar_total.iloc[i,5]) 

ar_total['lat_float']=lat_str_to_float
ar_total['lon_float']=lon_str_to_float

print(ar_total.head(5))

<class 'pandas.DataFrame'>
Index: 202727 entries, 0 to 14982
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   UnitID        202727 non-null  str
 1   EventCode     202727 non-null  str
 2   UTC_DateTime  202727 non-null  str
 3   Address       202727 non-null  str
 4   Latitude      202727 non-null  str
 5   Longitude     202727 non-null  str
 6   lat_float     202727 non-null  float64
 7   lon_float     202727 non-null  float64
dtypes: float64(2), str(6)
memory usage: 13.9 MB
   UnitID EventCode             UTC_DateTime  \
0  CGQ270      Stop  1/06/2026 12:00:00 a.m.
1  CGQ270     Drive   1/06/2026 8:05:16 a.m.
2  CGQ270     Drive   1/06/2026 8:05:32 a.m.
3  CGQ270     Drive   1/06/2026 8:06:59 a.m.
4  CGQ270     Drive   1/06/2026 8:08:19 a.m.

                                 Address  Latitude  Longitude lat_float  \
0  Kr14-85, Pitalito, Huila, Colombia     1,867038  -76,04412  1.867038
1  Kr14-86, Pitalito, Huila, Colombia     1,867019   -76,0441  1.867019
2  Kr14-92, Pitalito, Huila, Colombia     1,866782  -76,04388  1.866782
3         Cl31-92, Pitalito, Huila  Hul   1,866291  -76,04376  1.866291
4         Cl31-19, Pitalito, Huila  Hul   1,866018  -76,03423  1.866018

   lon_float
0  -76.04412
1   -76.0441
2  -76.04388
3  -76.04376
4  -76.03423

Scatter plot total of units reported with troubles

In [ ]:
x_axis=[]
y_axis=[]
unit=[]
df=pd.DataFrame()

for i in range(0,ar_total.shape[0]):
    try:
        x_axis.append(ar_total.iloc[i,6]*1000000)
        y_axis.append(ar_total.iloc[i,7]*100000)
        unit.append(ar_total.iloc[i,0])
    except:
        print(ar_total.iloc[i,6], ' -> ',ar_total.iloc[i,7])

df['Unit']=unit
df['Lat']=x_axis
df['Lon']=y_axis

sns.scatterplot(data=df, x='Lat', y='Lon', hue='Unit')

4.44087  ->  -74.0276
4.440376  ->  -74.03404
4.441821  ->  -74.03896
4.592129  ->  -74.22514
4.592306  ->  -74.22331
4.59221  ->  -74.22187
4.592324  ->  -74.22163
4.595968  ->  -74.22113
4.596008  ->  -74.21768
4.596008  ->  -74.2169
4.596458  ->  -74.21655
4.597692  ->  -74.21616
4.599038  ->  -74.21299
4.600963  ->  -74.21001
4.602633  ->  -74.20719
4.60201  ->  -74.20668
4.599082  ->  -74.20441
4.597542  ->  -74.20459
4.59716  ->  -74.20493
4.596644  ->  -74.20485
4.593289  ->  -74.20515
4.592923  ->  -74.20449
4.591333  ->  -74.20137
4.588623  ->  -74.19709
4.587291  ->  -74.19625
4.587487  ->  -74.1963
4.589872  ->  -74.19724
4.590147  ->  -74.19675
4.59253  ->  -74.19198
4.594112  ->  -74.18871
4.594207  ->  -74.18848
4.594122  ->  -74.18842
4.593355  ->  -74.18806
4.591934  ->  -74.18733
4.591274  ->  -74.18694
4.591599  ->  -74.18623
4.591727  ->  -74.18582
4.591688  ->  -74.18578
4.591539  ->  -74.18575
4.591519  ->  -74.18578
4.591292  ->  -74.18568
4.591271  ->  -74.18567
4.591258  ->  -74.18567
4.591353  ->  -74.18578
4.591557  ->  -74.18577
4.591635  ->  -74.18585
4.591505  ->  -74.18616

In [ ]:
print(' Max latitude: ',df['Lat'].max(),'Min latiude: ',df['Lat'].min(),'\n','Max longitude: ',df['Lon'].max(),'Min longitude: ',df['Lon'].min())

 Max latitude:  5.399373 Min latiude:  0.881136
 Max longitude:  -77.87443 Min longitude:  -73.50356

Scatter plot PRZ609