In [15]:
import pandas as pd
import numpy as np

Export Alerts Report from TSO.

4764429210	33333333		    85f	55,182

4764429242	972564107	BHI-774	85f	55,182

4764429241	972573025	BHA-863	85f	55,182

4764429268	987457988	BCZ-718	85f	55,182

4764428940	972565498	BCY-928	85f	55,182

In [16]:
alerts=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\Alerts Report.csv',sep=',')
alerts.info()

<class 'pandas.DataFrame'>
RangeIndex: 8205 entries, 0 to 8204
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GroupName    8088 non-null   str
 1   UnitName     8205 non-null   str
 2   textbox4     8205 non-null   str
 3   StartTime    8205 non-null   str
 4   ContactName  8150 non-null   str
 5   DriverName   8205 non-null   str
 6   textbox11    8205 non-null   str
dtypes: str(7)
memory usage: 448.8 KB

In [17]:
alerts['textbox4'].value_counts()

textbox4
Geofence Alert    6218
Idle Alert        1517
Speeding Alert     470
Name: count, dtype: int64

In [ ]:
idle_alert=alerts[alerts['textbox4'].str.contains('Idle')]
idle_alert['UnitName'].to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\Units.csv')

In [19]:
plate=input('Type the number plate: ')
idle_alert_1=idle_alert[idle_alert['UnitName'].str.contains(plate)]
idle_alert_1

Empty DataFrame
Columns: [GroupName, UnitName, textbox4, StartTime, ContactName, DriverName, textbox11]
Index: []

In [20]:
hl=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\don_pollo\historicallocations.xlsx - Sheet1.csv',sep=',')
hl.info()

<class 'pandas.DataFrame'>
RangeIndex: 2427 entries, 0 to 2426
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sequence     2427 non-null   int64
 1   Unit         2427 non-null   str
 2   Events       2427 non-null   str
 3   Date         2427 non-null   str
 4   Landmark     804 non-null    str
 5   Address      2427 non-null   str
 6   Speed        2427 non-null   int64
 7   Temperature  0 non-null      float64
 8   Driver       2427 non-null   str
 9   Latitude     2427 non-null   float64
 10  Longitude    2427 non-null   float64
dtypes: float64(3), int64(2), str(6)
memory usage: 208.7 KB

In [21]:
hl['Events'].value_counts()

Events
Drive           1173
Travel Start     236
Travel Stop      231
Landmark OUT     123
Landmark IN      116
Geofence IN      105
Ignition ON       97
Ignition OFF      95
Geofence OUT      94
Idle - Stop       87
Parked            49
Idle Alert        11
POWER UP          10
Name: count, dtype: int64

In [27]:
hl_travel_start=hl[hl['Events'].str.contains('Travel Start')]
hl_travel_start[['Date','Unit','Events','Speed']]

                      Date     Unit        Events  Speed
8     May 11 2026 09:44 AM  BCY-928  Travel Start     17
14    May 11 2026 09:37 AM  BCY-928  Travel Start     25
19    May 11 2026 09:34 AM  BCY-928  Travel Start     25
36    May 11 2026 09:11 AM  BCY-928  Travel Start     16
46    May 11 2026 08:57 AM  BCY-928  Travel Start     33
...                    ...      ...           ...    ...
2361  May 06 2026 04:31 AM  BCY-928  Travel Start     19
2377  May 06 2026 04:21 AM  BCY-928  Travel Start     20
2395  May 06 2026 04:07 AM  BCY-928  Travel Start     17
2419  May 06 2026 03:52 AM  BCY-928  Travel Start     14
2423  May 06 2026 03:51 AM  BCY-928  Travel Start      8

[236 rows x 4 columns]

In [30]:
hl_travel_start=hl[hl['Events'].str.contains('Idle')]
hl_travel_start[['Date','Unit','Events','Speed']]

                      Date     Unit       Events  Speed
0     May 11 2026 09:48 AM  BCY-928  Idle - Stop      0
38    May 11 2026 09:08 AM  BCY-928  Idle - Stop      0
47    May 11 2026 08:57 AM  BCY-928  Idle - Stop      0
114   May 11 2026 07:29 AM  BCY-928  Idle - Stop      0
125   May 11 2026 07:17 AM  BCY-928  Idle - Stop      0
...                    ...      ...          ...    ...
2363  May 06 2026 04:29 AM  BCY-928  Idle - Stop      0
2379  May 06 2026 04:20 AM  BCY-928   Idle Alert      0
2381  May 06 2026 04:18 AM  BCY-928  Idle - Stop      0
2424  May 06 2026 03:49 AM  BCY-928   Idle Alert      0
2425  May 06 2026 03:47 AM  BCY-928  Idle - Stop      0

[98 rows x 4 columns]

In [32]:
hl_idle_alert=hl[hl['Events'].str.contains('Alert')]
hl_idle_alert[['Date','Unit','Events','Speed']]

                      Date     Unit      Events  Speed
2184  May 06 2026 08:24 AM  BCY-928  Idle Alert      0
2188  May 06 2026 08:17 AM  BCY-928  Idle Alert      0
2199  May 06 2026 07:53 AM  BCY-928  Idle Alert      0
2211  May 06 2026 07:34 AM  BCY-928  Idle Alert      0
2272  May 06 2026 05:48 AM  BCY-928  Idle Alert      0
2329  May 06 2026 05:00 AM  BCY-928  Idle Alert     12
2341  May 06 2026 04:48 AM  BCY-928  Idle Alert      0
2349  May 06 2026 04:41 AM  BCY-928  Idle Alert      0
2362  May 06 2026 04:31 AM  BCY-928  Idle Alert      8
2379  May 06 2026 04:20 AM  BCY-928  Idle Alert      0
2424  May 06 2026 03:49 AM  BCY-928  Idle Alert      0