In [109]:
import pandas as pd
import numpy as np

869487062724710 with motion 30s. Colombian unit.

In [139]:
raw_data_869487062724710=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_2226_022026.csv',sep=',')
raw_data_869487062724710.info()
raw_data_869487062724710['Event Name'].value_counts()
print(raw_data_869487062724710.iloc[(raw_data_869487062724710.shape[0]-1),3],' -> ',raw_data_869487062724710.iloc[0,3])

<class 'pandas.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     1040 non-null   int64
 1   Sequence #                 1040 non-null   int64
 2   Account Id                 1040 non-null   int64
 3   Server Time                1040 non-null   str
 4   Unit Time                  1040 non-null   str
 5   Latitude                   1040 non-null   float64
 6   Longitude                  1040 non-null   float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 1040 non-null   str
 9   Raw Event                  1040 non-null   str
 10  GPS Speed                  1040 non-null   float64
 11  ECU Speed                  0 non-null      float64
 12  Address                    1040 non-null   str
 13  Landmark ID                6 non-null      float64
 14  Satellites                 1040 non-null   int64
 15  Distance                   1040 non-null   float64
 16  HDOP                       0 non-null      float64
 17  VDOP                       0 non-null      float64
 18  RSSI                       0 non-null      float64
 19  Engine Hours               1040 non-null   int64
 20  Engine Hours + Off         1040 non-null   int64
 21  ECU Engine Hours           1040 non-null   int64
 22  ECU Engine Hours + Off     1040 non-null   int64
 23  Engine Odometer            1040 non-null   float64
 24  Engine Odometer + Off      1040 non-null   float64
 25  ECU Engine Odometer        1040 non-null   int64
 26  ECU Engine Odometer + Off  1040 non-null   int64
 27  Battery Level              1040 non-null   int64
 28  Raw Data                   1040 non-null   str
dtypes: float64(12), int64(11), str(6)
memory usage: 235.8 KB
2026/02/24 15:22:33  ->  2026/02/26 10:37:07

In [140]:
motion=raw_data_869487062724710[raw_data_869487062724710['Event Name'].str.contains('Motion')]
only_motion=motion[~motion['Event Name'].str.contains('Motion S')]
#only_motion.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_2226_022026_motion.csv')

In [141]:
raw_data_869487062724710['Event Name'].value_counts()

Event Name
Motion          637
Update          347
Motion Stop      38
Motion Start     18
Name: count, dtype: int64

In [142]:
ts_events=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\troubleshootingevents_180b6743-112d-42d3-9203-4fd59fd20f62.csv',sep=',')
ts_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unit Time    211 non-null    str
 1   Data Center  211 non-null    str
 2   Voltage      0 non-null      float64
 3   Latitude     71 non-null     float64
 4   Longitude    71 non-null     float64
 5   Raw Event    211 non-null    str
 6   Event Name   211 non-null    str
 7   Heading      71 non-null     float64
 8   Sequence #   211 non-null    int64
 9   GPS Speed    71 non-null     float64
 10  Address      0 non-null      float64
 11  Unit Type    211 non-null    str
 12  Raw Data     211 non-null    str
dtypes: float64(6), int64(1), str(6)
memory usage: 21.6 KB

In [143]:
cont=0
for i in range(0,ts_events.shape[0]):
    if ts_events.iloc[i,6]=='User Update':
        cont=cont+1
        print('Event created on: ',ts_events.iloc[i,0])
print("Number of \'User Update\' events: ",cont)

Event created on:  2026/03/03 09:39:02 -05
Event created on:  2026/03/03 09:17:56 -05
Event created on:  2026/03/03 09:03:32 -05
Event created on:  2026/03/03 08:58:06 -05
Event created on:  2026/03/03 08:23:59 -05
Number of 'User Update' events:  5

869487062909196 wth motion 30s. Peruvian unit.

In [144]:
raw_data_869487062909196=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062909196_2226_022026.csv',sep=',')
raw_data_869487062909196.info()
print(raw_data_869487062909196.iloc[(raw_data_869487062909196.shape[0]-1),3],' -> ',raw_data_869487062909196.iloc[0,3])

<class 'pandas.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     124 non-null    int64
 1   Sequence #                 124 non-null    int64
 2   Account Id                 124 non-null    int64
 3   Server Time                124 non-null    str
 4   Unit Time                  124 non-null    str
 5   Latitude                   124 non-null    float64
 6   Longitude                  124 non-null    float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 124 non-null    str
 9   Raw Event                  124 non-null    str
 10  GPS Speed                  124 non-null    float64
 11  ECU Speed                  0 non-null      float64
 12  Address                    124 non-null    str
 13  Landmark ID                0 non-null      float64
 14  Satellites                 124 non-null    int64
 15  Distance                   124 non-null    float64
 16  HDOP                       0 non-null      float64
 17  VDOP                       0 non-null      float64
 18  RSSI                       0 non-null      float64
 19  Engine Hours               124 non-null    int64
 20  Engine Hours + Off         124 non-null    int64
 21  ECU Engine Hours           124 non-null    int64
 22  ECU Engine Hours + Off     124 non-null    int64
 23  Engine Odometer            124 non-null    float64
 24  Engine Odometer + Off      124 non-null    float64
 25  ECU Engine Odometer        124 non-null    int64
 26  ECU Engine Odometer + Off  124 non-null    int64
 27  Battery Level              124 non-null    int64
 28  Raw Data                   124 non-null    str
dtypes: float64(12), int64(11), str(6)
memory usage: 28.2 KB
2026/02/25 11:43:57  ->  2026/02/25 16:35:36

In [146]:
motion=raw_data_869487062909196[raw_data_869487062909196['Event Name'].str.contains('Motion')]
only_motion=motion[~motion['Event Name'].str.contains('Motion S')]
only_motion
#only_motion.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062909196_2226_022026_motion.csv')

,Row Id,Sequence #,Account Id,Server Time,Unit Time,Latitude,Longitude,Driver Name,Event Name,Raw Event,...,Engine Hours,Engine Hours + Off,ECU Engine Hours,ECU Engine Hours + Off,Engine Odometer,Engine Odometer + Off,ECU Engine Odometer,ECU Engine Odometer + Off,Battery Level,Raw Data
2,1772050936000,199,26305,2026/02/25 15:22:17,2026/02/25 15:22:16,-12.097868,-77.020515,NaN,Motion,02-M,...,0,0,0,0,7.0,7.0,0,0,95,272702004900c708694870629091964d00260225202216...
3,1772050906000,198,26305,2026/02/25 15:21:47,2026/02/25 15:21:46,-12.097506,-77.020805,NaN,Motion,02-M,...,0,0,0,0,6.9,6.9,0,0,95,272702004900c608694870629091964c00260225202146...
4,1772050876000,197,26305,2026/02/25 15:21:17,2026/02/25 15:21:16,-12.097506,-77.020805,NaN,Motion,02-M,...,0,0,0,0,6.9,6.9,0,0,95,272702004900c508694870629091964d00260225202116...
5,1772050846000,196,26305,2026/02/25 15:20:47,2026/02/25 15:20:46,-12.097506,-77.020805,NaN,Motion,02-M,...,0,0,0,0,6.9,6.9,0,0,95,272702004900c408694870629091964d00260225202046...
6,1772050816000,195,26305,2026/02/25 15:20:17,2026/02/25 15:20:16,-12.097466,-77.020973,NaN,Motion,02-M,...,0,0,0,0,6.9,6.9,0,0,95,272702004900c308694870629091964d00260225202016...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,1772039768000,65,26305,2026/02/25 12:16:38,2026/02/25 12:16:08,-12.097971,-77.021324,NaN,Motion,02-M,...,0,0,0,0,0.4,0.4,0,0,97,272702004900410869487062909196c900260225171608...
117,1772039738000,64,26305,2026/02/25 12:16:38,2026/02/25 12:15:38,-12.097971,-77.021324,NaN,Motion,02-M,...,0,0,0,0,0.4,0.4,0,0,98,2727020049004008694870629091964900260225171538...
118,1772039707000,63,26305,2026/02/25 12:15:23,2026/02/25 12:15:07,-12.097971,-77.021324,NaN,Motion,02-M,...,0,0,0,0,0.4,0.4,0,0,97,2727020049003f0869487062909196c900260225171507...
119,1772039677000,62,26305,2026/02/25 12:15:22,2026/02/25 12:14:37,-12.097971,-77.021324,NaN,Motion,02-M,...,0,0,0,0,0.4,0.4,0,0,98,2727020049003e08694870629091964900260225171437...
120,1772039652000,61,26305,2026/02/25 12:14:13,2026/02/25 12:14:12,-12.097971,-77.021324,NaN,Motion,02-M,...,0,0,0,0,0.4,0.4,0,0,98,2727020049003d08694870629091964900260225171412...

In [147]:
raw_data_869487062909196['Event Name'].value_counts()

Event Name
Motion          112
Update            5
Motion Stop       4
Motion Start      3
Name: count, dtype: int64

869487062905251 with motion 1min. Peruvian unit.

In [148]:
raw_data_869487062905251=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062905251_2226_022026.csv',sep=',')
raw_data_869487062905251.info()
print(raw_data_869487062905251.iloc[0,3],' -> ',raw_data_869487062905251.iloc[(raw_data_869487062905251.shape[0]-1),3],)

<class 'pandas.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     73 non-null     int64
 1   Sequence #                 73 non-null     int64
 2   Account Id                 73 non-null     int64
 3   Server Time                73 non-null     str
 4   Unit Time                  73 non-null     str
 5   Latitude                   73 non-null     float64
 6   Longitude                  73 non-null     float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 73 non-null     str
 9   Raw Event                  73 non-null     str
 10  GPS Speed                  73 non-null     float64
 11  ECU Speed                  0 non-null      float64
 12  Address                    73 non-null     str
 13  Landmark ID                0 non-null      float64
 14  Satellites                 73 non-null     int64
 15  Distance                   73 non-null     float64
 16  HDOP                       0 non-null      float64
 17  VDOP                       0 non-null      float64
 18  RSSI                       0 non-null      float64
 19  Engine Hours               73 non-null     int64
 20  Engine Hours + Off         73 non-null     int64
 21  ECU Engine Hours           73 non-null     int64
 22  ECU Engine Hours + Off     73 non-null     int64
 23  Engine Odometer            73 non-null     float64
 24  Engine Odometer + Off      73 non-null     float64
 25  ECU Engine Odometer        73 non-null     int64
 26  ECU Engine Odometer + Off  73 non-null     int64
 27  Battery Level              73 non-null     int64
 28  Raw Data                   73 non-null     str
dtypes: float64(12), int64(11), str(6)
memory usage: 16.7 KB
2026/02/25 16:06:04  ->  2026/02/25 12:26:22

In [149]:
motion=raw_data_869487062905251[raw_data_869487062905251['Event Name'].str.contains('Motion')]
only_motion=motion[~motion['Event Name'].str.contains('Motion S')]
only_motion
#only_motion.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062905251_2226_022026_motion.csv')

,Row Id,Sequence #,Account Id,Server Time,Unit Time,Latitude,Longitude,Driver Name,Event Name,Raw Event,...,Engine Hours,Engine Hours + Off,ECU Engine Hours,ECU Engine Hours + Off,Engine Odometer,Engine Odometer + Off,ECU Engine Odometer,ECU Engine Odometer + Off,Battery Level,Raw Data
1,1772051628000,155,26305,2026/02/25 15:34:34,2026/02/25 15:33:48,-12.096941,-77.020561,NaN,Motion,02-M,...,0,0,0,0,8.6,8.6,0,0,88,2727020049009b0869487062905251c700260225203348...
2,1772050906000,145,26305,2026/02/25 15:21:47,2026/02/25 15:21:46,-12.097475,-77.020798,NaN,Motion,02-M,...,0,0,0,0,8.5,8.5,0,0,89,2727020049009108694870629052514e00260225202146...
3,1772050846000,144,26305,2026/02/25 15:20:47,2026/02/25 15:20:46,-12.097475,-77.020798,NaN,Motion,02-M,...,0,0,0,0,8.5,8.5,0,0,88,2727020049009008694870629052514d00260225202046...
4,1772050785000,143,26305,2026/02/25 15:19:46,2026/02/25 15:19:45,-12.098737,-77.020897,NaN,Motion,02-M,...,0,0,0,0,8.4,8.4,0,0,88,2727020049008f08694870629052514c00260225201945...
5,1772050666000,142,26305,2026/02/25 15:18:09,2026/02/25 15:17:46,-12.101950,-77.019173,NaN,Motion,02-M,...,0,0,0,0,8.0,8.0,0,0,88,2727020049008e0869487062905251d300260225201746...
8,1772050551000,141,26305,2026/02/25 15:15:54,2026/02/25 15:15:51,-12.101821,-77.019089,NaN,Motion,02-M,...,0,0,0,0,8.0,8.0,0,0,89,2727020049008d08694870629052514e00260225201551...
9,1772050491000,140,26305,2026/02/25 15:14:54,2026/02/25 15:14:51,-12.101821,-77.019089,NaN,Motion,02-M,...,0,0,0,0,8.0,8.0,0,0,89,2727020049008c08694870629052514d00260225201451...
10,1772050431000,139,26305,2026/02/25 15:13:54,2026/02/25 15:13:51,-12.101821,-77.019089,NaN,Motion,02-M,...,0,0,0,0,8.0,8.0,0,0,89,2727020049008b08694870629052514e00260225201351...
11,1772050371000,138,26305,2026/02/25 15:12:54,2026/02/25 15:12:51,-12.102038,-77.017715,NaN,Motion,02-M,...,0,0,0,0,7.9,7.9,0,0,89,2727020049008a08694870629052514e00260225201251...
12,1772050311000,137,26305,2026/02/25 15:11:54,2026/02/25 15:11:51,-12.098525,-77.018715,NaN,Motion,02-M,...,0,0,0,0,7.6,7.6,0,0,89,2727020049008908694870629052514e00260225201151...
13,1772050251000,136,26305,2026/02/25 15:10:54,2026/02/25 15:10:51,-12.096834,-77.018394,NaN,Motion,02-M,...,0,0,0,0,7.5,7.5,0,0,89,2727020049008808694870629052514e00260225201051...
14,1772050191000,135,26305,2026/02/25 15:09:54,2026/02/25 15:09:51,-12.093179,-77.019371,NaN,Motion,02-M,...,0,0,0,0,7.2,7.2,0,0,89,2727020049008708694870629052514e00260225200951...
15,1772050131000,134,26305,2026/02/25 15:08:54,2026/02/25 15:08:51,-12.092012,-77.015350,NaN,Motion,02-M,...,0,0,0,0,6.9,6.9,0,0,89,2727020049008608694870629052514e00260225200851...
16,1772050071000,133,26305,2026/02/25 15:07:54,2026/02/25 15:07:51,-12.090671,-77.014259,NaN,Motion,02-M,...,0,0,0,0,6.7,6.7,0,0,89,2727020049008508694870629052514e00260225200751...
17,1772050011000,132,26305,2026/02/25 15:06:54,2026/02/25 15:06:51,-12.088919,-77.014709,NaN,Motion,02-M,...,0,0,0,0,6.6,6.6,0,0,89,2727020049008408694870629052514e00260225200651...
18,1772049951000,131,26305,2026/02/25 15:05:54,2026/02/25 15:05:51,-12.088223,-77.014557,NaN,Motion,02-M,...,0,0,0,0,6.4,6.4,0,0,89,2727020049008308694870629052514c00260225200551...
19,1772049891000,130,26305,2026/02/25 15:04:54,2026/02/25 15:04:51,-12.089181,-77.013680,NaN,Motion,02-M,...,0,0,0,0,6.3,6.3,0,0,89,2727020049008208694870629052514d00260225200451...
20,1772049831000,129,26305,2026/02/25 15:03:54,2026/02/25 15:03:51,-12.089188,-77.012856,NaN,Motion,02-M,...,0,0,0,0,6.2,6.2,0,0,90,2727020049008108694870629052514d00260225200351...
21,1772049771000,128,26305,2026/02/25 15:02:54,2026/02/25 15:02:51,-12.089139,-77.012299,NaN,Motion,02-M,...,0,0,0,0,6.2,6.2,0,0,89,2727020049008008694870629052514e00260225200251...
22,1772049711000,127,26305,2026/02/25 15:01:54,2026/02/25 15:01:51,-12.088559,-77.007721,NaN,Motion,02-M,...,0,0,0,0,5.9,5.9,0,0,89,2727020049007f08694870629052514e00260225200151...
23,1772049651000,126,26305,2026/02/25 15:00:54,2026/02/25 15:00:51,-12.089348,-77.007523,NaN,Motion,02-M,...,0,0,0,0,5.8,5.8,0,0,89,2727020049007e08694870629052514d00260225200051...
24,1772049591000,125,26305,2026/02/25 14:59:54,2026/02/25 14:59:51,-12.090393,-77.007881,NaN,Motion,02-M,...,0,0,0,0,5.7,5.7,0,0,89,2727020049007d08694870629052514e00260225195951...
25,1772049481000,124,26305,2026/02/25 14:58:04,2026/02/25 14:58:01,-12.089195,-77.005333,NaN,Motion,02-M,...,0,0,0,0,5.4,5.4,0,0,89,2727020049007c08694870629052515100260225195801...
26,1772044471000,115,26305,2026/02/25 13:34:32,2026/02/25 13:34:31,-12.090820,-77.005409,NaN,Motion,02-M,...,0,0,0,0,5.2,5.2,0,0,90,2727020049007308694870629052514e00260225183431...
27,1772044411000,114,26305,2026/02/25 13:33:32,2026/02/25 13:33:31,-12.089181,-77.005501,NaN,Motion,02-M,...,0,0,0,0,5.0,5.0,0,0,89,2727020049007208694870629052514e00260225183331...
28,1772044350000,113,26305,2026/02/25 13:32:32,2026/02/25 13:32:30,-12.088682,-77.005783,NaN,Motion,02-M,...,0,0,0,0,4.9,4.9,0,0,89,2727020049007108694870629052514e00260225183230...
29,1772044291000,112,26305,2026/02/25 13:31:32,2026/02/25 13:31:31,-12.088732,-77.006401,NaN,Motion,02-M,...,0,0,0,0,4.9,4.9,0,0,90,2727020049007008694870629052514e00260225183131...
30,1772044231000,111,26305,2026/02/25 13:30:32,2026/02/25 13:30:31,-12.087716,-77.007820,NaN,Motion,02-M,...,0,0,0,0,4.7,4.7,0,0,89,2727020049006f08694870629052514d00260225183031...
31,1772044171000,110,26305,2026/02/25 13:29:32,2026/02/25 13:29:31,-12.084834,-77.008446,NaN,Motion,02-M,...,0,0,0,0,4.5,4.5,0,0,89,2727020049006e08694870629052514e00260225182931...
32,1772044111000,109,26305,2026/02/25 13:28:32,2026/02/25 13:28:31,-12.084834,-77.008446,NaN,Motion,02-M,...,0,0,0,0,4.5,4.5,0,0,89,2727020049006d08694870629052514e00260225182831...
33,1772044051000,108,26305,2026/02/25 13:27:32,2026/02/25 13:27:31,-12.084512,-77.011833,NaN,Motion,02-M,...,0,0,0,0,4.3,4.3,0,0,89,2727020049006c08694870629052514d00260225182731...
34,1772043991000,107,26305,2026/02/25 13:26:33,2026/02/25 13:26:31,-12.087822,-77.013290,NaN,Motion,02-M,...,0,0,0,0,4.0,4.0,0,0,89,2727020049006b08694870629052514e00260225182631...
35,1772043930000,106,26305,2026/02/25 13:25:32,2026/02/25 13:25:30,-12.089158,-77.012642,NaN,Motion,02-M,...,0,0,0,0,3.9,3.9,0,0,90,2727020049006a08694870629052515500260225182530...
39,1772043540000,104,26305,2026/02/25 13:19:01,2026/02/25 13:19:00,-12.088955,-77.011604,NaN,Motion,02-M,...,0,0,0,0,3.8,3.8,0,0,90,2727020049006808694870629052514e00260225181900...
40,1772043480000,103,26305,2026/02/25 13:18:01,2026/02/25 13:18:00,-12.088955,-77.011604,NaN,Motion,02-M,...,0,0,0,0,3.8,3.8,0,0,90,2727020049006708694870629052514e00260225181800...
41,1772043420000,102,26305,2026/02/25 13:17:02,2026/02/25 13:17:00,-12.088811,-77.011124,NaN,Motion,02-M,...,0,0,0,0,3.8,3.8,0,0,90,2727020049006608694870629052514e00260225181700...
42,1772043360000,101,26305,2026/02/25 13:16:01,2026/02/25 13:16:00,-12.088162,-77.011200,NaN,Motion,02-M,...,0,0,0,0,3.8,3.8,0,0,90,2727020049006508694870629052514d00260225181600...
43,1772043300000,100,26305,2026/02/25 13:15:01,2026/02/25 13:15:00,-12.087856,-77.011681,NaN,Motion,02-M,...,0,0,0,0,3.7,3.7,0,0,90,2727020049006408694870629052514e00260225181500...
44,1772043240000,99,26305,2026/02/25 13:14:01,2026/02/25 13:14:00,-12.087396,-77.013290,NaN,Motion,02-M,...,0,0,0,0,3.5,3.5,0,0,90,2727020049006308694870629052514d00260225181400...
45,1772043180000,98,26305,2026/02/25 13:13:01,2026/02/25 13:13:00,-12.086101,-77.015106,NaN,Motion,02-M,...,0,0,0,0,3.3,3.3,0,0,90,2727020049006208694870629052514e00260225181300...
46,1772043120000,97,26305,2026/02/25 13:12:01,2026/02/25 13:12:00,-12.088614,-77.014618,NaN,Motion,02-M,...,0,0,0,0,3.1,3.1,0,0,90,2727020049006108694870629052514e00260225181200...
47,1772043060000,96,26305,2026/02/25 13:11:01,2026/02/25 13:11:00,-12.092073,-77.014191,NaN,Motion,02-M,...,0,0,0,0,2.9,2.9,0,0,90,2727020049006008694870629052514d00260225181100...
48,1772043000000,95,26305,2026/02/25 13:10:01,2026/02/25 13:10:00,-12.092073,-77.014191,NaN,Motion,02-M,...,0,0,0,0,2.9,2.9,0,0,90,2727020049005f08694870629052514e00260225181000...
49,1772042940000,94,26305,2026/02/25 13:09:01,2026/02/25 13:09:00,-12.092658,-77.015694,NaN,Motion,02-M,...,0,0,0,0,2.7,2.7,0,0,90,2727020049005e08694870629052514e00260225180900...
50,1772042880000,93,26305,2026/02/25 13:08:01,2026/02/25 13:08:00,-12.094928,-77.018379,NaN,Motion,02-M,...,0,0,0,0,2.4,2.4,0,0,90,2727020049005d08694870629052514e00260225180800...
51,1772042820000,92,26305,2026/02/25 13:07:01,2026/02/25 13:07:00,-12.097759,-77.018600,NaN,Motion,02-M,...,0,0,0,0,2.2,2.2,0,0,90,2727020049005c08694870629052514e00260225180700...
52,1772042760000,91,26305,2026/02/25 13:06:01,2026/02/25 13:06:00,-12.097699,-77.018929,NaN,Motion,02-M,...,0,0,0,0,2.2,2.2,0,0,90,2727020049005b08694870629052514d00260225180600...
53,1772042700000,90,26305,2026/02/25 13:05:01,2026/02/25 13:05:00,-12.097727,-77.019997,NaN,Motion,02-M,...,0,0,0,0,2.1,2.1,0,0,90,2727020049005a08694870629052514d00260225180500...
54,1772042640000,89,26305,2026/02/25 13:04:03,2026/02/25 13:04:00,-12.097727,-77.019997,NaN,Motion,02-M,...,0,0,0,0,2.1,2.1,0,0,90,2727020049005908694870629052514c00260225180400...
55,1772042574000,88,26305,2026/02/25 13:02:55,2026/02/25 13:02:54,-12.098294,-77.020020,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049005808694870629052515000260225180254...
57,1772041348000,82,26305,2026/02/25 12:42:28,2026/02/25 12:42:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049005208694870629052514a00260225174228...
58,1772041288000,81,26305,2026/02/25 12:41:28,2026/02/25 12:41:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049005108694870629052514b00260225174128...
59,1772041228000,80,26305,2026/02/25 12:40:29,2026/02/25 12:40:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049005008694870629052514b00260225174028...
60,1772041168000,79,26305,2026/02/25 12:39:56,2026/02/25 12:39:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,91,2727020049004f08694870629052514b00260225173928...
61,1772041108000,78,26305,2026/02/25 12:38:32,2026/02/25 12:38:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049004e08694870629052514b00260225173828...
62,1772041047000,77,26305,2026/02/25 12:37:47,2026/02/25 12:37:27,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049004d08694870629052514900260225173727...
63,1772040988000,76,26305,2026/02/25 12:36:58,2026/02/25 12:36:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049004c08694870629052514d00260225173628...
64,1772040928000,75,26305,2026/02/25 12:36:09,2026/02/25 12:35:28,-12.098000,-77.020813,NaN,Motion,02-M,...,0,0,0,0,1.9,1.9,0,0,90,2727020049004b08694870629052514c00260225173528...

In [150]:
raw_data_869487062905251['Event Name'].value_counts()

Event Name
Motion          58
Update           8
Motion Stop      4
Motion Start     3
Name: count, dtype: int64

GL300W comparison:

In [151]:
raw_data=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\Export_gl300w.csv',sep=',')
hl=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\historicallocationsgl300w.csv',sep=',')
aux_m=[]

for i in range(0,raw_data.shape[0]):
    aux_m.append(raw_data.iloc[i,1][6:11])
raw_data['Message_Type']=aux_m

raw_data['Message_Type'].value_counts()
hl['Events'].value_counts()

Events
Parked              7147
Idle - Stop         1515
Drive               1418
Speed alert          153
Stopped Charging      24
Power Cut             24
Power Restored        24
Start Charging        21
Battery Warning       12
Self Test/Reboot       1
Name: count, dtype: int64

Because of Queclink GL300W does not have a similar event to "Update", for TopFly Knight, Update can be set to 6 hours. This was confirmed bY Gerardo Loaiza on Friday 27-02-2026.

# Script with the first edition.

869487062724710 with motion 30s. Colombian unit.

In [153]:
raw_data_869487062724710=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710.csv',sep=',')
raw_data_869487062724710['Event Name'].value_counts()

Event Name
Motion          193
Update           94
Motion Stop       9
User Update       9
Motion Start      7
Name: count, dtype: int64

Date of panic button:

9:44, 9:44 -> 2026/03/06 9:44:43

9:45 -> 2026/03/06 9:45:17

9:46 -> 2026/03/06 9:46:17

9:48 -> 2026/03/06 9:48:38

9:50 -> 2026/03/06 9:50:17

9:51 -> 2026/03/06 9:51:56

9:53 -> 2026/03/06 9:53:17

9:58 -> 2026/03/06 9:58:35

10:09 -> 2026/03/06 10:08:54

10:10 (indoor) Without register.

In [154]:
raw_data_869487062724710_user_update=raw_data_869487062724710[raw_data_869487062724710['Event Name'].str.contains('User Update')]
raw_data_869487062724710_user_update[['Server Time','Unit Time','Latitude','Longitude','Event Name']]

            Server Time            Unit Time  Latitude  Longitude   Event Name
26  2026/03/06 10:08:54  2026/03/06 10:08:37  3.464569 -76.525940  User Update
35   2026/03/06 9:58:35   2026/03/06 9:58:34  3.464569 -76.525940  User Update
46   2026/03/06 9:53:17   2026/03/06 9:53:17  3.463692 -76.525360  User Update
49   2026/03/06 9:51:56   2026/03/06 9:51:56  3.463189 -76.525772  User Update
53   2026/03/06 9:50:17   2026/03/06 9:50:17  3.462468 -76.526176  User Update
57   2026/03/06 9:48:38   2026/03/06 9:48:38  3.463259 -76.526871  User Update
62   2026/03/06 9:46:17   2026/03/06 9:46:17  3.463941 -76.526634  User Update
64   2026/03/06 9:45:17   2026/03/06 9:45:17  3.464389 -76.526573  User Update
66   2026/03/06 9:44:43   2026/03/06 9:44:42  3.465162 -76.525902  User Update

In [155]:
raw_data_869487062724710_motion=raw_data_869487062724710[raw_data_869487062724710['Event Name'].str.contains('Motion')]
raw_data_869487062724710_motion_filtered=raw_data_869487062724710_motion[['Server Time','Unit Time','Latitude','Longitude','Sequence #','Event Name']]
#raw_data_869487062724710_motion.info()
raw_data_869487062724710_motion_filtered.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_motion_30s.csv')

In [156]:
raw_data_869487062724710_motion_filtered['Server Time'].value_counts()

Server Time
2026/03/02 7:26:50     3
2026/03/06 10:22:44    2
2026/03/01 12:51:28    2
2026/03/06 10:25:17    1
2026/03/06 10:25:14    1
                      ..
2026/03/01 10:56:50    1
2026/03/01 10:56:26    1
2026/03/01 10:55:56    1
2026/03/01 10:55:26    1
2026/03/01 10:54:55    1
Name: count, Length: 205, dtype: int64

In [157]:
ts_events_869487062724710=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\troubleshootingevents_869487062724710.csv',sep=',')
ts_events_869487062724710['Event Name'].value_counts()

Event Name
Comm Acquired    152
Motion            58
Update            29
Device Info       19
Motion Start      14
Motion Stop       11
User Update        8
Name: count, dtype: int64

In [158]:
ts_events_869487062724710_user_update=ts_events_869487062724710[ts_events_869487062724710['Event Name'].str.contains('User Update')]
ts_events_869487062724710_user_update[['Unit Time','Latitude','Longitude','Event Name']]

                   Unit Time  Latitude  Longitude   Event Name
2    2026/03/06 09:44:21 -05       0.0        0.0  User Update
25   2026/03/06 08:50:12 -05       0.0        0.0  User Update
54   2026/03/05 14:31:06 -05       0.0        0.0  User Update
94   2026/03/03 09:39:02 -05       0.0        0.0  User Update
100  2026/03/03 09:17:56 -05       0.0        0.0  User Update
103  2026/03/03 09:03:32 -05       0.0        0.0  User Update
105  2026/03/03 08:58:06 -05       0.0        0.0  User Update
118  2026/03/03 08:23:59 -05       0.0        0.0  User Update

In [159]:
ts_events_869487062724710['Unit Time'].value_counts()

Unit Time
2026/03/06 09:42:02 -05    2
2026/03/06 08:45:31 -05    2
2026/03/05 21:51:55 -05    2
2026/03/05 10:17:29 -05    2
2026/03/03 22:37:53 -05    2
                          ..
2026/02/28 20:49:48 -05    1
2026/02/28 20:29:47 -05    1
2026/02/28 20:09:45 -05    1
2026/02/28 19:35:45 -05    1
2026/02/28 19:25:46 -05    1
Name: count, Length: 285, dtype: int64

869487062724710 with motion 1min. Colombian unit.

In [160]:
raw_data_869487062724710=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_0610_0326.csv',sep=',')
raw_data_869487062724710['Event Name'].value_counts()

Event Name
Motion          445
Motion Stop      31
User Update      16
Motion Start     15
Update            7
Name: count, dtype: int64

In [161]:
raw_data_869487062724710_user_update=raw_data_869487062724710[raw_data_869487062724710['Event Name'].str.contains('User Update')]
raw_data_869487062724710_user_update[['Server Time','Unit Time','Latitude','Longitude','Event Name']]

,Server Time,Unit Time,Latitude,Longitude,Event Name
3,2026/03/10 10:48:13,2026/03/10 10:48:13,3.464750,-76.525917,User Update
5,2026/03/10 10:46:11,2026/03/10 10:46:11,3.463747,-76.525299,User Update
6,2026/03/10 10:45:10,2026/03/10 10:45:10,3.463123,-76.525719,User Update
7,2026/03/10 10:44:05,2026/03/10 10:44:04,3.462577,-76.526245,User Update
8,2026/03/10 10:42:41,2026/03/10 10:42:41,3.463151,-76.526970,User Update
10,2026/03/10 10:41:18,2026/03/10 10:41:18,3.463962,-76.526649,User Update
11,2026/03/10 10:39:59,2026/03/10 10:39:59,3.464663,-76.526474,User Update
473,2026/03/06 10:08:54,2026/03/06 10:08:37,3.464569,-76.525940,User Update
482,2026/03/06 09:58:35,2026/03/06 09:58:34,3.464569,-76.525940,User Update
493,2026/03/06 09:53:17,2026/03/06 09:53:17,3.463692,-76.525360,User Update
496,2026/03/06 09:51:56,2026/03/06 09:51:56,3.463189,-76.525772,User Update
500,2026/03/06 09:50:17,2026/03/06 09:50:17,3.462468,-76.526176,User Update
504,2026/03/06 09:48:38,2026/03/06 09:48:38,3.463259,-76.526871,User Update
509,2026/03/06 09:46:17,2026/03/06 09:46:17,3.463941,-76.526634,User Update
511,2026/03/06 09:45:17,2026/03/06 09:45:17,3.464389,-76.526573,User Update
513,2026/03/06 09:44:43,2026/03/06 09:44:42,3.465162,-76.525902,User Update

In [162]:
raw_data_869487062724710_motion=raw_data_869487062724710[raw_data_869487062724710['Event Name'].str.contains('Motion')]
raw_data_869487062724710_motion_filtered=raw_data_869487062724710_motion[['Server Time','Unit Time','Latitude','Longitude','Sequence #','Event Name']]
#raw_data_869487062724710_motion.info()
raw_data_869487062724710_motion_filtered.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_motion_1min.csv')

In [163]:
raw_data_869487062724710_motion_filtered['Server Time'].value_counts()

Server Time
2026/03/07 22:04:45    2
2026/03/06 10:22:44    2
2026/03/10 10:52:02    1
2026/03/10 10:51:24    1
2026/03/10 10:49:23    1
                      ..
2026/03/06 09:47:50    1
2026/03/06 09:47:19    1
2026/03/06 09:46:48    1
2026/03/06 09:45:48    1
2026/03/06 09:45:00    1
Name: count, Length: 489, dtype: int64

Date of panic button:

10:39 -> 2026/03/10 10:39:59

10:40 -> 2026/03/10 10:41:18

10:41 -> 2026/03/10 10:42:41

10:42 -> 2026/03/10 10:42:41

10:44 -> 2026/03/10 10:44:04

10:45 -> 2026/03/10 10:45:10

10:46 -> 2026/03/10 10:46:11

10:48 -> 2026/03/10 10:48:13

869487062909196 with motion 30s. Peruvian unit.

In [164]:
raw_data_869487062909196=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062909196_1011_032026.csv',sep=',')
raw_data_869487062909196.info()

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     165 non-null    int64
 1   Sequence #                 165 non-null    int64
 2   Account Id                 165 non-null    int64
 3   Server Time                165 non-null    str
 4   Unit Time                  165 non-null    str
 5   Latitude                   165 non-null    float64
 6   Longitude                  165 non-null    float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 165 non-null    str
 9   Raw Event                  165 non-null    str
 10  GPS Speed                  165 non-null    float64
 11  ECU Speed                  0 non-null      float64
 12  Address                    165 non-null    str
 13  Landmark ID                0 non-null      float64
 14  Satellites                 165 non-null    int64
 15  Distance                   165 non-null    float64
 16  HDOP                       0 non-null      float64
 17  VDOP                       0 non-null      float64
 18  RSSI                       0 non-null      float64
 19  Engine Hours               165 non-null    int64
 20  Engine Hours + Off         165 non-null    int64
 21  ECU Engine Hours           165 non-null    int64
 22  ECU Engine Hours + Off     165 non-null    int64
 23  Engine Odometer            165 non-null    float64
 24  Engine Odometer + Off      165 non-null    float64
 25  ECU Engine Odometer        165 non-null    int64
 26  ECU Engine Odometer + Off  165 non-null    int64
 27  Battery Level              165 non-null    int64
 28  Raw Data                   165 non-null    str
dtypes: float64(12), int64(11), str(6)
memory usage: 37.5 KB

In [165]:
raw_data_869487062909196_user_update=raw_data_869487062909196[raw_data_869487062909196['Event Name'].str.contains('User Update')]
raw_data_869487062909196_user_update[['Server Time','Unit Time','Latitude','Longitude','Event Name']]

,Server Time,Unit Time,Latitude,Longitude,Event Name
22,2026/03/10 15:53:01,2026/03/10 15:53:00,-12.117382,-77.005997,User Update
77,2026/03/10 15:24:37,2026/03/10 15:24:37,-12.117382,-77.005997,User Update
79,2026/03/10 15:24:10,2026/03/10 15:24:00,-12.117479,-77.005997,User Update

In [166]:
raw_data_869487062909196_motion=raw_data_869487062909196[raw_data_869487062909196['Event Name'].str.contains('Motion')]
raw_data_869487062909196_motion_filtered=raw_data_869487062909196_motion[['Server Time','Unit Time','Latitude','Longitude','Sequence #','Event Name']]
#raw_data_869487062724710_motion_filtered
raw_data_869487062909196_motion_filtered.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062909196_motion_30s.csv')

869487062905251 with motion 1 min. Peruvian unit.

In [167]:
raw_data_869487062905251=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062905251_1011_032026.csv',sep=',')
raw_data_869487062905251.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     84 non-null     int64
 1   Sequence #                 84 non-null     int64
 2   Account Id                 84 non-null     int64
 3   Server Time                84 non-null     str
 4   Unit Time                  84 non-null     str
 5   Latitude                   84 non-null     float64
 6   Longitude                  84 non-null     float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 84 non-null     str
 9   Raw Event                  84 non-null     str
 10  GPS Speed                  84 non-null     float64
 11  ECU Speed                  0 non-null      float64
 12  Address                    84 non-null     str
 13  Landmark ID                0 non-null      float64
 14  Satellites                 84 non-null     int64
 15  Distance                   84 non-null     float64
 16  HDOP                       0 non-null      float64
 17  VDOP                       0 non-null      float64
 18  RSSI                       0 non-null      float64
 19  Engine Hours               84 non-null     int64
 20  Engine Hours + Off         84 non-null     int64
 21  ECU Engine Hours           84 non-null     int64
 22  ECU Engine Hours + Off     84 non-null     int64
 23  Engine Odometer            84 non-null     float64
 24  Engine Odometer + Off      84 non-null     float64
 25  ECU Engine Odometer        84 non-null     int64
 26  ECU Engine Odometer + Off  84 non-null     int64
 27  Battery Level              84 non-null     int64
 28  Raw Data                   84 non-null     str
dtypes: float64(12), int64(11), str(6)
memory usage: 19.2 KB

In [168]:
raw_data_869487062905251_user_update=raw_data_869487062905251[raw_data_869487062905251['Event Name'].str.contains('User Update')]
raw_data_869487062905251_user_update[['Server Time','Unit Time','Latitude','Longitude','Event Name']]

,Server Time,Unit Time,Latitude,Longitude,Event Name
9,2026/03/10 15:52:53,2026/03/10 15:52:51,-12.117308,-77.006012,User Update
36,2026/03/10 15:24:21,2026/03/10 15:24:19,-12.117610,-77.006172,User Update
37,2026/03/10 15:23:51,2026/03/10 15:23:49,-12.117610,-77.006172,User Update

In [171]:
raw_data_869487062905251_motion=raw_data_869487062905251[raw_data_869487062905251['Event Name'].str.contains('Motion')]
raw_data_869487062905251_motion_filtered=raw_data_869487062905251_motion[['Server Time','Unit Time','Latitude','Longitude','Sequence #','Event Name']]
#raw_data_869487062724710_motion_filtered
raw_data_869487062905251_motion_filtered.to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062905251_motion_1min.csv')

I found Stop events without Start events in Raw Data.

In [217]:
unit_869487062724710_1min=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_motion_1min.csv',sep=',')
print("Data since: ",unit_869487062724710_1min.iloc[unit_869487062724710_1min.shape[0]-1,1]," until ", unit_869487062724710_1min.iloc[0,1])
unit_869487062724710_1min['Event Name'].value_counts()

Data since:  2026/03/06 09:45:00  until  2026/03/10 10:52:02

Event Name
Motion          445
Motion Stop      31
Motion Start     15
Name: count, dtype: int64

In [218]:
ts_unit_869487062724710_1min=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\troubleshootingevents_869487062724710_0610_032026.csv',sep=',')
print("Data since: ",ts_unit_869487062724710_1min.iloc[ts_unit_869487062724710_1min.shape[0]-1,0]," until ", ts_unit_869487062724710_1min.iloc[0,0])
ts_unit_869487062724710_1min['Event Name'].value_counts()

Data since:  2026/03/05 21:51:55 -05  until  2026/03/10 18:44:18 -05

Event Name
Motion           57
Comm Acquired    55
Device Info      29
Motion Start     22
Motion Stop       9
Update            9
User Update       3
Name: count, dtype: int64

In [225]:
motion=pd.concat([ts_unit_869487062724710_1min[['Event Name','Unit Time']],unit_869487062724710_1min[['Event Name','Unit Time']]])
motion_filtered=motion[motion['Event Name'].str.contains('Motion S')]
motion_filtered.sort_values('Unit Time').to_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\motion_filtered1.csv')
motion['Event Name'].value_counts()

Event Name
Motion           502
Comm Acquired     55
Motion Stop       40
Motion Start      37
Device Info       29
Update             9
User Update        3
Name: count, dtype: int64

In [202]:
unit_869487062724710_30s=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062724710_motion_30s.csv',sep=',')
print("Data since: ",unit_869487062724710_30s.iloc[unit_869487062724710_30s.shape[0]-1,1]," until ", unit_869487062724710_30s.iloc[0,1])
unit_869487062724710_30s['Event Name'].value_counts()

Data since:  2026/03/01 10:54:55  until  2026/03/06 10:25:17

Event Name
Motion          193
Motion Stop       9
Motion Start      7
Name: count, dtype: int64

In [203]:
unit_869487062905251_1min=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062905251_motion_1min.csv',sep=',')
print("Data since: ",unit_869487062905251_1min.iloc[unit_869487062905251_1min.shape[0]-1,1]," until ",unit_869487062905251_1min.iloc[0,1])
unit_869487062905251_1min['Event Name'].value_counts()

Data since:  2026/03/10 10:13:40  until  2026/03/10 16:02:17

Event Name
Motion          74
Motion Stop      4
Motion Start     3
Name: count, dtype: int64

In [204]:
unit_869487062909196_30s=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\projects\data\zonar\rawdata_869487062909196_motion_30s.csv',sep=',')
print("Data since: ",unit_869487062909196_30s.iloc[unit_869487062909196_30s.shape[0]-1,1]," until ",unit_869487062909196_30s.iloc[0,1])
unit_869487062909196_30s['Event Name'].value_counts()

Data since:  2026/03/10 10:14:03  until  2026/03/10 20:56:08

Event Name
Motion          154
Motion Stop       6
Motion Start      1
Name: count, dtype: int64