In [56]:
import pandas as pd 
import numpy as np
import datetime         #Shows in my time zone COL.

In [57]:
vf=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080 vf 20-22.csv',sep=';')
vf.info()

<class 'pandas.DataFrame'>
RangeIndex: 1834 entries, 0 to 1833
Data columns (total 34 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Raw Data     1834 non-null   str
 1   Unnamed: 1   1834 non-null   str
 2   Unnamed: 2   1834 non-null   str
 3   Unnamed: 3   1834 non-null   str
 4   Unnamed: 4   1834 non-null   str
 5   Unnamed: 5   1834 non-null   str
 6   Unnamed: 6   1834 non-null   str
 7   Unnamed: 7   1834 non-null   str
 8   Unnamed: 8   1834 non-null   str
 9   Unnamed: 9   1834 non-null   str
 10  Unnamed: 10  1834 non-null   str
 11  Unnamed: 11  1834 non-null   str
 12  Unnamed: 12  1834 non-null   str
 13  Unnamed: 13  1834 non-null   str
 14  Unnamed: 14  1834 non-null   str
 15  Unnamed: 15  1834 non-null   str
 16  Unnamed: 16  1834 non-null   str
 17  Unnamed: 17  1834 non-null   str
 18  Unnamed: 18  1834 non-null   str
 19  Unnamed: 19  1834 non-null   str
 20  Unnamed: 20  1039 non-null   str
 21  Unnamed: 21  259 non-null    str
 22  Unnamed: 22  259 non-null    str
 23  Unnamed: 23  127 non-null    str
 24  Unnamed: 24  127 non-null    str
 25  Unnamed: 25  127 non-null    str
 26  Unnamed: 26  127 non-null    str
 27  Unnamed: 27  74 non-null     str
 28  Unnamed: 28  74 non-null     str
 29  Unnamed: 29  74 non-null     str
 30  Unnamed: 30  33 non-null     str
 31  Unnamed: 31  5 non-null      str
 32  Unnamed: 32  5 non-null      str
 33  Unnamed: 33  5 non-null      str
dtypes: str(34)
memory usage: 487.3 KB

In [58]:
vf['Unnamed: 3'].value_counts()

Unnamed: 3
\"notificationType\":\"TripInfo\"          1622
\"notificationType\":\"AutoSnapshot\"       137
\"notificationType\":\"CameraEvent\"         53
\"notificationType\":\"IgnitionStatus\"      22
Name: count, dtype: int64

Camera event

In [59]:
vf_camera_events=vf[vf['Unnamed: 3'].str.contains('CameraEvent')]
vf_camera_events['Unnamed: 5'].value_counts()

Unnamed: 5
\"eventCategory\":\"LANE_DEPARTURE\"         42
\"eventCategory\":\"STOP_SIGN_VIOLATION\"    10
\"eventCategory\":\"HEADWAY_MONITORING\"      1
Name: count, dtype: int64

In [60]:
vf_autosnapshot=vf[vf['Unnamed: 3'].str.contains('AutoSnapshot')]
time_ign_on=[]
time_ign_off=[]
autosnapshot=[]
vf_autosnapshot_time=pd.DataFrame()

for i in range(0,vf_autosnapshot.shape[0]):
    aux=float(vf_autosnapshot.iloc[i,7][19:33])/1000
    time_ign_on.append(datetime.datetime.fromtimestamp(aux))
    aux=float(vf_autosnapshot.iloc[i,8][20:34])/1000
    time_ign_off.append(datetime.datetime.fromtimestamp(aux))
    autosnapshot.append(vf_autosnapshot.iloc[i,11])

vf_autosnapshot_time['last_time_ign_on']=time_ign_on
vf_autosnapshot_time['last_time_ign_off']=time_ign_off
vf_autosnapshot_time['URL']=autosnapshot

vf_autosnapshot_time.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080 vf 20-22 autoSnapShot.csv')

#vf_autosnapshot[['Unnamed: 11','Unnamed: 7','Unnamed: 8']].to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080 vf 20-22 autoSnapShot.csv')

In [61]:
ign_on=[]
ign_off=[]
ign_on_col=[]
ign_off_col=[]
ign_time=pd.DataFrame()

vf_camera_events_ignition=vf[vf['Unnamed: 3'].str.contains('Ignition')]
for i in range(0,vf_camera_events_ignition.shape[0]):

    ign_on.append(vf_camera_events_ignition.iloc[i,8][19:33])
    aux=float(vf_camera_events_ignition.iloc[i,8][19:33])/1000
    ign_on_col.append(datetime.datetime.fromtimestamp(aux))

    ign_off.append(vf_camera_events_ignition.iloc[i,9][20:33])
    aux=float(vf_camera_events_ignition.iloc[i,9][20:34])/1000
    ign_off_col.append(datetime.datetime.fromtimestamp(aux))    

ign_time['epoch_ign_on']=ign_on
ign_time['epoch_ign_on_col']=ign_on_col
ign_time['epoch_ign_off']=ign_off
ign_time['epoch_ign_off_col']=ign_off_col

ign_time.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080_ign.csv')

PM

In [62]:
vf_pm=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080 vf 20_22_pm.csv',sep=',')
vf_pm.info()

<class 'pandas.DataFrame'>
RangeIndex: 1834 entries, 0 to 1833
Data columns (total 50 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Row Id                     1834 non-null   int64
 1   Sequence #                 0 non-null      float64
 2   Server Time                1834 non-null   str
 3   Unit Time                  1834 non-null   str
 4   Last Message Time          1834 non-null   str
 5   Latitude                   1834 non-null   float64
 6   Longitude                  1834 non-null   float64
 7   Driver Name                0 non-null      float64
 8   Event Name                 1834 non-null   str
 9   Raw Event                  1834 non-null   str
 10  Address                    1834 non-null   str
 11  GPS Speed                  1145 non-null   float64
 12  ECU Speed                  0 non-null      float64
 13  Speed Limit                860 non-null    float64
 14  Heading                    1826 non-null   float64
 15  Ignition Status            1834 non-null   str
 16  Notification Type          1834 non-null   str
 17  Trip Id                    1834 non-null   str
 18  Picture Id                 137 non-null    float64
 19  Event Category             53 non-null     str
 20  Event Level                53 non-null     str
 21  Camera Clip Key            53 non-null     float64
 22  Camera Clip Offset         53 non-null     float64
 23  Clip Id                    53 non-null     float64
 24  Duration                   0 non-null      float64
 25  Rotate                     137 non-null    str
 26  Camera Status              0 non-null      float64
 27  Idle Status                1622 non-null   str
 28  SDCard Status              0 non-null      float64
 29  Data Usage In KB           0 non-null      float64
 30  Transaction Id             0 non-null      float64
 31  Status                     0 non-null      float64
 32  Error Msg                  0 non-null      float64
 33  Valid Time Range           0 non-null      float64
 34  Warning                    0 non-null      float64
 35  Distance                   1834 non-null   float64
 36  Accumulated Distance       1571 non-null   float64
 37  Engine Hours               1834 non-null   float64
 38  Engine Hours + Off         1834 non-null   float64
 39  ECU Engine Hours           1834 non-null   int64
 40  ECU Engine Hours + Off     1834 non-null   int64
 41  Engine Odometer            1834 non-null   float64
 42  Engine Odometer + Off      1834 non-null   float64
 43  ECU Engine Odometer        1834 non-null   int64
 44  ECU Engine Odometer + Off  1834 non-null   int64
 45  HDOP                       212 non-null    float64
 46  VDOP                       0 non-null      float64
 47  RSSI                       0 non-null      float64
 48  Battery Level              0 non-null      float64
 49  Raw Data                   1834 non-null   str
dtypes: float64(31), int64(5), str(14)
memory usage: 716.5 KB

In [63]:
vf_pm_21_08=vf_pm[vf_pm['Unit Time'].str.contains('2026/08/21')]
vf_pm_21_08['Event Name'].value_counts()

Event Name
Idle                   402
Drive                  287
AutoSnapshot            53
Travel Start            23
Travel Stop             22
Lane Departure          10
Ignition Off             3
Stop Sign Violation      3
Ignition On              3
Name: count, dtype: int64

In [64]:
vf_pm_ignitions=vf_pm_21_08[vf_pm_21_08['Event Name'].str.contains('Ignition')]
vf_pm_ignitions

,Row Id,Sequence #,Server Time,Unit Time,Last Message Time,Latitude,Longitude,Driver Name,Event Name,Raw Event,...,ECU Engine Hours + Off,Engine Odometer,Engine Odometer + Off,ECU Engine Odometer,ECU Engine Odometer + Off,HDOP,VDOP,RSSI,Battery Level,Raw Data
171,178734961929,NaN,2026/08/21 17:00:19,2026/08/21 16:50:00,2026/08/21 17:00:20,10.616557,-75.276742,NaN,Ignition Off,IgnitionStatus.parking,...,0,39405.99,39405.99,0,0,0.8,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."
272,178734500058,NaN,2026/08/21 15:43:21,2026/08/21 15:32:05,2026/08/21 15:43:22,10.616984,-75.452678,NaN,Ignition Off,IgnitionStatus.parking,...,0,39387.25,39387.25,0,0,0.7,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."
586,178732886795,NaN,2026/08/21 11:14:28,2026/08/21 11:03:55,2026/08/21 11:14:29,10.956948,-74.908680,NaN,Ignition Off,IgnitionStatus.parking,...,0,39225.28,39225.28,0,0,0.7,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."
933,178731342634,NaN,2026/08/21 06:57:06,2026/08/21 06:56:54,2026/08/21 06:57:07,10.662864,-74.912012,NaN,Ignition On,IgnitionStatus.driving,...,0,39154.42,39154.42,0,0,0.7,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."
934,178732940656,NaN,2026/08/21 11:23:27,2026/08/21 06:56:54,2026/08/21 11:23:27,10.662864,-74.912012,NaN,Ignition On,IgnitionStatus.driving,...,0,39188.34,39188.33,0,0,0.7,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."
935,178734612110,NaN,2026/08/21 16:02:01,2026/08/21 06:56:54,2026/08/21 16:02:01,10.662864,-74.912012,NaN,Ignition On,IgnitionStatus.driving,...,0,39286.77,39286.76,0,0,0.7,NaN,NaN,NaN,"""{\""ingestVersion\"":\""1.0.4\"",\""linkedMode\"":1..."

TopFly Piooneer

In [65]:
pioneer_pm=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\chilco\qor080 pionner.csv',sep=',')
pioneer_pm['Event Name'].value_counts()

Event Name
Drive           2360
Idle            1154
Ignition Off      18
Ignition On       18
Travel Stop        4
Travel Start       4
Name: count, dtype: int64

In [66]:
pioneer_pm_21=pioneer_pm[pioneer_pm['Unit Time'].str.contains('2026/08/21')]
pioneer_pm_21_ignition=pioneer_pm_21[pioneer_pm_21['Event Name'].str.contains('Ignition')]
pioneer_pm_21_ignition

,Row Id,Sequence #,Account Id,Server Time,Unit Time,Latitude,Longitude,Driver Name,Event Name,Raw Event,...,Engine Hours,Engine Hours + Off,ECU Engine Hours,ECU Engine Hours + Off,Engine Odometer,Engine Odometer + Off,ECU Engine Odometer,ECU Engine Odometer + Off,Battery Level,Raw Data
183,178735292506,NaN,29550,2026/08/21 17:55:25,2026/08/21 17:55:05,10.639135,-74.924911,NaN,Ignition Off,02,...,2420.09,0.67,0,0,16210.88,16210.88,0,0,NaN,"{""unitId"":""869487064344087"",""intUnitID"":111600..."
184,178735293057,NaN,29550,2026/08/21 17:55:31,2026/08/21 17:55:05,10.639135,-74.924911,NaN,Ignition Off,02,...,2420.09,0.67,0,0,16210.88,16210.88,0,0,NaN,"{""unitId"":""869487064344087"",""intUnitID"":111600..."
1634,178731340704,NaN,29550,2026/08/21 06:56:47,2026/08/21 06:56:27,10.662895,-74.912094,NaN,Ignition On,01,...,2409.11,0.66,0,0,16058.74,16058.74,0,0,NaN,"{""unitId"":""869487064344087"",""intUnitID"":111600..."
1635,178731340718,NaN,29550,2026/08/21 06:56:47,2026/08/21 06:56:27,10.662895,-74.912094,NaN,Ignition On,01,...,2409.11,0.66,0,0,16058.74,16058.74,0,0,NaN,"{""unitId"":""869487064344087"",""intUnitID"":111600..."