In [35]:
import pandas as pd
import numpy as np

Template from TSO:

In [36]:
units_from_tso=pd. read_excel(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\zonar\UnitsProvision.xlsx')
units_from_tso.info()

<class 'pandas.DataFrame'>
RangeIndex: 2881 entries, 0 to 2880
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UnitID        2881 non-null   str
 1   SerialNumber  1004 non-null   str
 2   IMEI          999 non-null    str
 3   SimNo         788 non-null    str
 4   Carrier       1077 non-null   str
 5   AreaCode      342 non-null    str
 6   PhoneNumber   628 non-null    str
 7   StaticIP      151 non-null    str
 8   ModemName     947 non-null    str
 9   Paired        2881 non-null   bool
dtypes: bool(1), str(9)
memory usage: 205.5 KB

c:\Users\Jose.Hurtado\Documents\Zonar_projects\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [37]:
units=pd.read_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\zonar\CARGA MASIVA_14.05.25_HERO.csv',sep=';')
units.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UnitID        200 non-null    str
 1   SerialNumber  200 non-null    int64
 2   IMEI          200 non-null    int64
 3   SimNo         200 non-null    int64
 4   Carrier       200 non-null    str
 5   AreaCode      200 non-null    int64
 6   PhoneNumber   200 non-null    int64
 7   StaticIP      0 non-null      float64
 8   ModemName     200 non-null    str
 9   Paired        200 non-null    bool
dtypes: bool(1), float64(1), int64(5), str(3)
memory usage: 14.4 KB

In [38]:
units['SerialNumber'] = units['SerialNumber'].astype(str)
units['IMEI'] = units['IMEI'].astype(str)
units['SimNo'] = units['SerialNumber'].astype(str)
units['AreaCode'] = units['AreaCode'].astype(str)
units['PhoneNumber'] = units['PhoneNumber'].astype(str)
units['StaticIP'] = units['StaticIP'].astype(str)

In [39]:
units.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UnitID        200 non-null    str
 1   SerialNumber  200 non-null    str
 2   IMEI          200 non-null    str
 3   SimNo         200 non-null    str
 4   Carrier       200 non-null    str
 5   AreaCode      200 non-null    str
 6   PhoneNumber   200 non-null    str
 7   StaticIP      0 non-null      str
 8   ModemName     200 non-null    str
 9   Paired        200 non-null    bool
dtypes: bool(1), str(9)
memory usage: 14.4 KB

In [40]:
pd_f1=units[units['UnitID'].str.contains(' ')]
pd_f1

Empty DataFrame
Columns: [UnitID, SerialNumber, IMEI, SimNo, Carrier, AreaCode, PhoneNumber, StaticIP, ModemName, Paired]
Index: []

In [41]:
pd_f2=units[units['Carrier'].str.contains(' ')]
pd_f2

Empty DataFrame
Columns: [UnitID, SerialNumber, IMEI, SimNo, Carrier, AreaCode, PhoneNumber, StaticIP, ModemName, Paired]
Index: []

In [42]:
pd_f3=units[units['ModemName'].str.contains(' ')]
pd_f3

Empty DataFrame
Columns: [UnitID, SerialNumber, IMEI, SimNo, Carrier, AreaCode, PhoneNumber, StaticIP, ModemName, Paired]
Index: []

In [43]:
units.to_csv(r'C:\Users\Jose.Hurtado\Documents\Zonar_projects\data\zonar\units_provision_test.csv')